### ISSUE TITLE
Crash w/ Shatter Mod

### ISSUE THREAD

**Issue by WenXin20** [henkelmax/ultimate-car-mod#10]
**Bug description**
- My game crashed client-side after joining a server world that had the mod Shatter installed.

**Steps to reproduce the issue**
1. Install Shatter
2. Load world
3. Crash

**Expected behavior**
- No crashes.

**Log files**
- [Crash Report](https://gist.github.com/WenXin20/c7293111a4acc5dc90053939bc0a64a0)

**Versions**
- `Minecraft v1.15.2`
- `Forge v31.2.45`
- `Ultimate Car v2.0.12`
- [`Shatter v8.0.1`](https://www.curseforge.com/minecraft/mc-mods/shatter)

**Comment by henkelmax** [comment]
Unfortunately, I am not able to reproduce this issue with just Shatter and the car mod.

Please try narrowing down your mods until you know which mod causes this crash.

**Comment by WenXin20** [comment]
The shatter effect only happens when a mob dies. I removed shatter and got no more crashes.
But I'll see if I can reproduce it.

**Comment by henkelmax** [comment]
> The shatter effect only happens when a mob dies. I removed shatter and got no more crashes.
> But I'll see if I can reproduce it.

Why don't you write that in the steps to reproduce?

I'm now able to reproduce the crahs.

**Comment by WenXin20** [comment]
> Why don't you write that in the steps to reproduce?
Thanks! I hadn't because I thought it crashed during world load, not when something died. In hindsight, I should've, but I hadn't thought of that.
