### ISSUE TITLE
I can't spawn cars in my forge server

### ISSUE THREAD

**Issue by xSharky** [henkelmax/ultimate-car-mod#101]
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**

**Bug description**
The car workshop shows a preview of the car, but when I press spawn car nothing happens

**Steps to reproduce the issue**
1. Start a forge server
2. Go to a car workshop
3. Click on spawn car
4. Nothing will happen

**Expected behavior**
A car should've spawn

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version: 1.19
- Forge version: 1.19
- Mod version: car-1.19-1.0.10.jar

**Other mods**
A list of the other mods that were installed when this problem occurred.
xaeros minimap 
MrCrayfish's furniture mod

**Screenshots (Optional)**
Screenshots of the issue.
![image](https://user-images.githubusercontent.com/109345854/179192799-11cd2ba4-5f9f-4f38-a183-5d009737c648.png)

**Comment by henkelmax** [comment]
Thanks for reporting this issue!
