### ISSUE TITLE
Suggest For Painter Tool

### ISSUE THREAD

**Issue by n0uremam** [henkelmax/ultimate-car-mod#102]
**Is your feature request related to a problem? Please describe.**
Suggestion for painter tool that really helps make the street more realistic.

**Describe the solution you'd like**
I had the idea adding in paint tool is adding bike line sign is will make the design of the street more realistic 

**Addit
![Bike-lane-e12826874326651](https://user-images.githubusercontent.com/84910254/179359669-9e645267-a778-404e-8532-e93b76bb2756.jpg)
ional context**
![1](https://user-images.githubusercontent.com/84910254/179359708-ddeb3a13-0bee-4c1d-aa1f-212da7adade2.png)

**Comment by henkelmax** [comment]
Would you have a prototype texture for that?

**Comment by n0uremam** [comment]
sorry I can't because I never created any texture before. But I really want to help if I could

**Comment by henkelmax** [comment]
I don't know hot to get such an icon in 16x16 pixels.

**Comment by n0uremam** [comment]
![bicycle_sign_icon_flat_black_white_geometric_symmetric_sketch_6921650](https://user-images.githubusercontent.com/84910254/179360812-3f5d4b0f-a908-4364-ae41-e50b898ce1cb.png)
![download-icon-bike-1321215613151110872_512](https://user-images.githubusercontent.com/84910254/179360814-05a36bc5-4e66-4453-bdc2-6cadf48a9f9e.png)

**Comment by n0uremam** [comment]
those 16x16 pixels bike icon

**Comment by henkelmax** [comment]
I don't now if you understand what 16x16 means

**Comment by n0uremam** [comment]
no sorry I don't understand what does it means, my apologies.

**Comment by ItsNoahiPad** [comment]
it is when you draw somthing but its just a pixel then add on to that

**Comment by ItsNoahiPad** [comment]
one question what size would the pixel drawing be

**Comment by ItsNoahiPad** [comment]
does this work
![download](https://user-images.githubusercontent.com/105044969/205038995-9cdbbab3-b1f2-43e3-8792-b2fe36bfe99b.png)

**Comment by n0uremam** [comment]
yes, it will do the job, thank you for following up ❤️

**Comment by n0uremam** [comment]
> one question what size would the pixel drawing be

same size like arrow
