### ISSUE TITLE
Car mod

### ISSUE THREAD

**Issue by emyvivi** [henkelmax/ultimate-car-mod#104]
Hello, I have noticed that when you insert  the "Ultimate car mod" into minecraft and launch the game it crashes and appears with this code "The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Registry Object not present: car:engine_stop
Exit Code: -1" is there a possibility to fix this if so thanks.

**Comment by henkelmax** [comment]
Please fill out the bug template
