### ISSUE TITLE
cars wont spawn

### ISSUE THREAD

**Issue by LTGaming2009** [henkelmax/ultimate-car-mod#105]
For some reason cars wont spawn when crafting them on my 1.19 java server. I have watched the video Mr. crayfish video and I didn't help. I'm sorry that I cant give more detail then they just wont spawn. I have put required items in the 3 by 3 grid (which I'm lucky I figured that out) and pressed spawn car. then the car doesn't spawn.  if there's a specific way to do it please get back to me, I really want this to work. 
![2022-08-06_21 17 57](https://user-images.githubusercontent.com/110637852/183271083-f03e3f66-5b06-4678-b651-5d59834704a8.png)
edit: i recently used the /cardemo command to get a car however i would still like for car crafting to be fixed for 1.19 because the cars spawn with wheels but then they disappear. but on top of not being able to craft, you cant repair a car either on the station. Please fix the mod. i also have some other mods installed such as mr cray fishes gun mod, the ultimate plane mod, fabric API, extra armor mod, extra weapons mod, another furniture mod, and frame work. when i restart the server it doesnt say anything unusual. im sorry that i cant say anything then when i click spawn car it just doesnt work.

**Comment by henkelmax** [comment]
Please fill out the bug template. I can't help you if you don't provide the necessary information.
