### ISSUE TITLE
Not sure if bug, or I'm just missing something

### ISSUE THREAD

**Issue by Semation** [henkelmax/ultimate-car-mod#108]
Every time I try to install this mod I keep getting the same error message: java.lang.NullPointerException: Registry Object not present: car:canola_seeds

I've tried to make sure I've got all the dependencies, but I'm still getting this message. I have: Jade, JEI, The One Probe, and Ultimate Plane Mod. Am I missing a dependency that I don't know of?
[crash-2022-08-12_15.05.54-fml.txt](https://github.com/henkelmax/ultimate-car-mod/files/9329647/crash-2022-08-12_15.05.54-fml.txt)

**Comment by henkelmax** [comment]
I just checked it and I am not able to reproduce your issue. Please try if this happens without any other mods.
