### ISSUE TITLE
ground lines affect the rendering

### ISSUE THREAD

**Issue by ink717** [henkelmax/ultimate-car-mod#11]
Minecraft Forge 1.16.3 (34.1.5+) with Optifine

This won't happen in most places, only in this city, where all lines were replaced by the lines from this mod.
As soon as I left the city far enough, everything goes back to normal.

This didn't cause any error or crash. I'm assuming it's an issue with texture or Optifine. Only in this city where an enormous amount of pavement lines was used had this problem. While we started replacing vanilla textures and filling these lines, it didn't happen at all until recent days when we completed a full replacement across the entire city. 

I tried changing settings in shaders and optifine, nothing worked out.

![2020-10-30_22 21 14](https://user-images.githubusercontent.com/72815511/97769146-ddcac180-1afe-11eb-8d48-09e18e167785.png)
![2020-10-30_22 20 36](https://user-images.githubusercontent.com/72815511/97769141-d4415980-1afe-11eb-8b2c-939869d48857.png)
![2020-10-30_22 20 16](https://user-images.githubusercontent.com/72815511/97769137-cee40f00-1afe-11eb-912b-04515f6353e2.png)
![2020-10-30_22 19 43](https://user-images.githubusercontent.com/72815511/97769136-cbe91e80-1afe-11eb-97a1-da9d25e063df.png)
![2020-10-30_22 21 01](https://user-images.githubusercontent.com/72815511/97769142-d7d4e080-1afe-11eb-95bb-0523a5ce7df5.png)

**Comment by henkelmax** [comment]
Does this happen without shaders?

**Comment by ink717** [comment]
No. Without shader is totally working normal. If I select the (internal) shader in Optifine, it still works fine.

I tried with all settings of Sildurs and SEUS. These all don’t work.

On Oct 31, 2020, at 5:27 AM, Max Henkel <notifications@github.com> wrote:

﻿

Does this happen without shaders?

**Comment by henkelmax** [comment]
This may be a bug of the shaders. Try reporting it to OptiFine or the shader creators.
