### ISSUE TITLE
Damage system

### ISSUE THREAD

**Issue by Workersteve** [henkelmax/ultimate-car-mod#110]
Hello , why i cant damage the cars with guns or bow or tnt? 
Is there something in config or the cars cant damage with them?! 
If they cant can you please add them?
And another question...
Can you please add planes mod for minecraft 1.12.2?
Because many players stopped at 1.12.2 version
I know 1.12.2 is old but many players will start downloading that great mod!

**Comment by henkelmax** [comment]
Tjere won't be anything for 1.12

**Comment by henkelmax** [comment]
Cars can only be damaged by liquids or crashing

**Comment by Workersteve** [comment]
Ok thanks
