### ISSUE TITLE
Make gas station compatible with Create fluid pipes

### ISSUE THREAD

**Issue by BlackJamesYT** [henkelmax/ultimate-car-mod#117]
I have a server with Ultimate Car and [Create](https://www.curseforge.com/minecraft/mc-mods/create) (and many other mods). I used Fluid extractors from Ultimate Car but they use too many resources so I use Create to extract fluids.
Generators can connect to the Create pipes and it fully works but not for Gas Station. I have to put a Tank and put a fluid extractor to connect to Gas Station.
![image](https://user-images.githubusercontent.com/19538750/197328552-cf1263ea-73da-4743-ab66-111d3f01ff1c.png)
It can be cool if the Gas Station is native compatible 🙂

**Comment by henkelmax** [comment]
The gas station works like every other machine in this mod. No fluid cables from the mod needed.
