### ISSUE TITLE
[net.minecraft.client.multiplayer.ClientPacketListener/]: Unknown custom packet identifier: car:default

### ISSUE THREAD

**Issue by rotoforze** [henkelmax/ultimate-car-mod#120]
**Bug description**
I have a modpack for my firends server. And when i were going to do a car it happend. right clicked workshop block and game crashed. I think is client side cz server did not crash (others were playing when that happen). Console just say "... disconected. reason: disconected."

**Steps to reproduce the issue**
1. Place car workshop block and 8 car workshop parts
2. right click workshop block

**Expected behavior**
Other mod that prevent this packet to be identified.

**Log files**
https://gist.github.com/rotoforze/ca479c757fcd1055291e3dd730fe3ee3

**Versions**
- MC ver: 1.18.2
- Forge ver: 40.1.80
- Mod ver: 1.0.1

**Other mods**
https://gist.github.com/rotoforze/c2a7e2423a396e8532ec069ebfe51c11

**Comment by rotoforze** [comment]
Okay? I re joined into the server and now i can open the table XD. Anyway i will wait for some help to know what were wrong.

**Comment by henkelmax** [comment]
> Okay? I re joined into the server and now i can open the table XD. Anyway i will wait for some help to know what were wrong.

So it works now?

**Comment by henkelmax** [comment]
Closed due to inactivity

**Comment by rotoforze** [comment]
It works now, idk what caused that. I guess other mod interacted and it crashed. 

Sorry for inactivity, gmail put it in spam and i got noticed when u closed xddd
