### ISSUE TITLE
Fluid pipe and cable don't connect to the machines(e.g: oil mil)

### ISSUE THREAD

**Issue by amandexspeed** [henkelmax/ultimate-car-mod#121]
**Bug description**
I made all the machines to produce fuel and I can't connect them to make the fuel

**Steps to reproduce the issue**
1. Make the machines
2. Put the fuel extractor
3. Put the fluid pipe
4. See error( They don't connect)

**Expected behavior**
The fluid pipe connect to the machines 

**Versions**
- Minecraft version: 1.19.2
- Forge version: 42.1.52
- Mod version 1.0

**Comment by amandexspeed** [comment]
Here's a screenshot:

![2022-11-19_17 22 34](https://user-images.githubusercontent.com/60000299/202870306-c4a5047e-a218-4865-96a5-a6d0a5b37815.png)

**Comment by henkelmax** [comment]
![image](https://user-images.githubusercontent.com/13237524/202900345-fa3c1e38-68f0-4dcc-bc98-555c69fd89a9.png)

Works perfectly fine

**Comment by amandexspeed** [comment]
Thanks, I'll remove the mod that is causing the problem
