### ISSUE TITLE
Cable doesn't connect to advices - v..1.19.2

### ISSUE THREAD

**Issue by Ruidisemos** [henkelmax/ultimate-car-mod#122]
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**

**Bug description**
When I try to connect the dynamo with the oil mill, i can't. (If you can explain me in Spanish, i'll thank you)

**Steps to reproduce the issue**
1. Just create a world on minecraft (survival or creative)
2. Try to connect the items
3. See error

**Expected behavior**
I need to know how to fix the problem or what to do with.

**Versions**
- Minecraft version 1.19.2
- Forge version 43.1.52
- Mod version 1.19.2-1.0.0.

**Other mods**
- backpacked-2.1.10-1.19
- blueprint-1.19.2-6.1.0.jar
- Croptopia-1.19.2-FORGE-2.1.0.jar
- FallingTree-1.19.2-3.10.0.jar
- goblintraders-1.8.0-1.19.2.jar
- Jade-1.19.1-forge-8.4.1.jar
- jei-1.19.2-forge-11.4.0.285.jar
- Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13.jar
- PrettyPipes-1.13.6.jar
- savage_and_ravage-1.19-5.0.2.jar
- SimpleCoreLib-1.19.2-5.1.0.0.jar
- SimpleOres2-1.19.2-5.1.1.8-all.jar
- TerraBlender-forge-1.19.2-2.0.1.129.jar
- Xaeros_Minimap_22.16.2_Forge_1.19.1.jar

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/118693018/202926828-73c6007e-4fb1-4f8b-bc1e-3cc9f50dfe32.png)

**Comment by henkelmax** [comment]
Works perfectly fine:
![image](https://user-images.githubusercontent.com/13237524/202990195-426aa650-63a2-450a-b10f-b764f24fb63e.png)


Might be related to #121
