### ISSUE TITLE
i got an sugestion

### ISSUE THREAD

**Issue by ItsNoahiPad** [henkelmax/ultimate-car-mod#123]
so i was thinking you should make it so you can put the icons on the asphalt stairs or on block on the side

**Comment by henkelmax** [comment]
I'm sorry, but this is not possible, as these blocks are not full blocks, so you can't put anything on top.

**Comment by ItsNoahiPad** [comment]
oh

**Comment by ItsNoahiPad** [comment]
what about on the side of a block
