### ISSUE TITLE
Summon car with name/tag

### ISSUE THREAD

**Issue by simpelMIC** [henkelmax/ultimate-car-mod#129]
Is it possible to summon a random car with a name or a Tag?
These are the commands I've tested:
`/summon car:car ~ ~ ~ {CustomName:"car"}`
`/summon car:car ~ ~ ~ {Tags: ["car"]}`
This spawns a car. But the car is invisible and when you destroy it, it doesn't drop anything.
This also happens with "Team" and "Score".

**Comment by henkelmax** [comment]
You can't summon cars with names. You also can't summon cars with NBT data if you don't supply any car parts in the NBT.
Just /summon car without NBT spawns a random car.

**Comment by simpelMIC** [comment]
Ok how can you supply car parts?

**Comment by henkelmax** [comment]
Look at the NBT data of an existing car.

**Comment by simpelMIC** [comment]
How exactly can I look at NBT Data from an entity?

**Comment by henkelmax** [comment]
`/data get entity @e[type=car:car,limit=1,sort=nearest]` gives you the data of the closest car

**Comment by simpelMIC** [comment]
Thx I'll try it
