### ISSUE TITLE
Ultimate Car Mod 1.16.4 every car is brown

### ISSUE THREAD

**Issue by MaXxDrew** [henkelmax/ultimate-car-mod#13]
Regardless of what color i am making the car body, it will come out brown. That's all that it is to it.

Steps to get the issue
 1. Create a car body out of any concrete colored block
 2. Put the item in the workstation
 3. The car body will result brown

Versions:
- Minecraft version: 1.16.4
- Forge version: 35.0.7
- Mod version: 1.0.4

Other mods:
   Ultimate Plane Mod (mod version: 1.0.1)
  Just Enough Items (mod version: 7.6.0.58)

![2020-11-16_00 20 27](https://user-images.githubusercontent.com/74513258/99198513-c7309580-27a1-11eb-9b8a-ab02732675a6.png)

![2020-11-16_00 20 44](https://user-images.githubusercontent.com/74513258/99198512-c0a21e00-27a1-11eb-8328-5ed26d8e1354.png)

![2020-11-16_00 15 09](https://user-images.githubusercontent.com/74513258/99198509-baac3d00-27a1-11eb-87d8-623359b77e0b.png)

![2020-11-16_00 15 07](https://user-images.githubusercontent.com/74513258/99198494-ae27e480-27a1-11eb-84c7-fa2e855a7639.png)

**Comment by henkelmax** [comment]
Brown is the base color of every car, just the accent color changes.
Look at the first image on curseforge.
