### ISSUE TITLE
Add cfg option to disable Canola seed and biofuel machines

### ISSUE THREAD

**Issue by tabr** [henkelmax/ultimate-car-mod#132]
**Is your feature request related to a problem? Please describe.**
For example, i have a big mod for oil refinery and don't need canola seed. Also, ImmersiveEngeneering have a biodiesel an bioethanol.

**Describe the solution you'd like**
CFG option to remove canola seed drop and refinery machines.

**Comment by henkelmax** [comment]
https://www.curseforge.com/minecraft/mc-mods/crafttweaker

**Comment by tabr** [comment]
Can't find how in CT 1.19 disable seed drop:(
