### ISSUE TITLE
Cables don't connect when mod is used with optifine

### ISSUE THREAD

**Issue by Edtheprof** [henkelmax/ultimate-car-mod#136]
**Bug description**
Cables and fluid pipes not connecting properly to other blocks

**Steps to reproduce the issue**
Go on minecraft with Optifine

**Expected behavior**
Cables don't connect with anything and fluid pipes don't connect to certain blocks

Version - 1.19.2

**Other mods**
Optifine and Create

**Comment by henkelmax** [comment]
Optifine is not supported. It breaks a lot of mods. Consider using alternative mods.
