### ISSUE TITLE
game crashes and breaks when destroying breaking gas station block. every single time i break gas station game crash. idk why but this must be fixed. invalied invalied invalied invalied invalied invalied gas station block crash game me. idk why but this fix must be a final fix. this is not a duplicate i always crash when break gas station. invalied . gas station block fix pls

### ISSUE THREAD

**Issue by chortle3** [henkelmax/ultimate-car-mod#140]
game crashes and breaks when destroying breaking gas station block. every single time i break gas station game crash. idk why but this must be fixed. invalied invalied invalied invalied invalied invalied gas station block crash game me. idk why but this fix must be a final fix. this is not a duplicate i always crash when break gas station. invalied . gas station block fix pls

**Comment by henkelmax** [comment]
Please properly use the bug template.
