### ISSUE TITLE
server crashes when placing gas station

### ISSUE THREAD

**Issue by ninglerjames** [henkelmax/ultimate-car-mod#145]
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**

**Bug description**
Anytime I place a gas station block, the server instantly crashes.

**Steps to reproduce the issue**
1. Place a gas station on a server

**Expected behavior**
The server shouldn't crash

**Log files**
https://pastebin.com/siST2zbq

**Versions**
- Minecraft version 1.16.5
- Forge version 36.2.39
- Mod version 1.0.17

**Other mods**
cgm-1.2.6
cofh core-1.5.2.22
ensorcellation-1.5.0.4
obfuscate-0.6.2
ultimate plane mod-1.0.9
project mmo-3.69.0

**Comment by henkelmax** [comment]
This has been fixed in newer versions.
