### ISSUE TITLE
Cannot fill Canister (gas can) with fuel - No Instructions

### ISSUE THREAD

**Issue by Tursiops-G** [henkelmax/ultimate-car-mod#148]
**Bug description**
Cannot fill Canister ("Gas Can") with Fuel (Biodiesel), either by putting it into the Pump slot, or Right-clicking it on a Tank of Fuel.
How do you do it? There's No Instructions in the Wiki on How to fill the Canister.

**Versions**
Forge 1.20.1
1.0.6

**Comment by Tursiops-G** [comment]
D'OH!

Thank You!

I could SWEAR I looked thru the Wiki link Several Times, and I cannot for the life of me see how I could have missed that... 😮

**Comment by Tursiops-G** [comment]
Before I make another Fool out of myself again, Is there any way to determine the fill status of the Transporter Tank?
I know you can use Buckets to add/remove fluid from the tank, but I can't find a GUI that shows me How Much fluid is actually in the tank (0-64,000mB) at any given time?

Thanks. :)

**Comment by henkelmax** [comment]
HWYLA or the one probe should show the contents

**Comment by Tursiops-G** [comment]
Can't seem to see it... Have The One Probe already set to not need the hand probe...
![image](https://github.com/henkelmax/ultimate-car-mod/assets/97983160/68bfe848-4a60-4cbb-98d6-c82bdd340879)

**Comment by Tursiops-G** [comment]
This is a bit awkward...
Do you have a Forum (Discord, Reddit, etc) that takes questions/feedback?

**Comment by henkelmax** [comment]
> Can't seem to see it... Have The One Probe already set to not need the hand probe...

Then it might be Jade that shows the contents. I can't really remember...

**Comment by Tursiops-G** [comment]
Jade is showing more info, but not correctly (?)...
![image](https://github.com/henkelmax/ultimate-car-mod/assets/97983160/9180708c-bc49-4d51-9c89-747030d2bfb1)

The Transport Tank has just been filled w/64 buckets of Biodiesel.

**Comment by Tursiops-G** [comment]
No Change with Version 1.0.7
