### ISSUE TITLE
everytime i play on 1.15.2, 1.16.2 , 1.16.3 1.16.4 and i click with right click on gas station i have that crash report The game crashed whilst unexpected error Error: java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidUtil.getFluidContained(Lnet/minecraft/item/ItemStack;)Lnet/minecraftforge/common/util/LazyOptional; Kod zakończenia: -1 i tested it with others mods and without mods also i reinstalled mod and forge

### ISSUE THREAD

**Issue by Dominusnews** [henkelmax/ultimate-car-mod#15]
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**

**Bug description**

**Steps to reproduce the issue**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version
- Forge version
- Mod version

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Please fill out the template.
The title should only be a very short description.
