### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Exanadu** [henkelmax/ultimate-car-mod#151]
Would it be possible to add stop signs and street name signs (other road signs as well such as speed limit yield etc.) maybe street lights in the future?

**Comment by henkelmax** [comment]
There are already other mods that add these blocks.
https://www.curseforge.com/minecraft/mc-mods/road-stuff

**Comment by Exanadu** [comment]
aye but that one hasn't had signs since 1.7.10 and isn't even updated for 1.20.1 :),  also your mod is the only road mod included currently in the FTB unstable 1.20 modpack that we are running on the server. But I understand
