### ISSUE TITLE
Request Fabric version

### ISSUE THREAD

**Issue by SadEPa0628** [henkelmax/ultimate-car-mod#156]
**Bug description**
No Fabric version

**Steps to reproduce the issue**
1. Go to PCL
2. Click on “下载”
3.Search"终极汽车"
4. See no Fabric version

**Expected behavior**
Make Fabric versions

**Versions**
- Minecraft 1.20.2
- Fabric 0.14.23
- no

**Screenshots (Optional)**
![image](https://github.com/henkelmax/ultimate-car-mod/assets/120295331/51132346-a20f-4ac0-b97f-2cc9328b10f3)

**Comment by henkelmax** [comment]
This isn't an official page of the mod. Please download mods from unofficial places as they might contain viruses.

**Comment by SadEPa0628** [comment]
Well, it doesn't matter. I mean, I hope there's a Fabric version

**Comment by henkelmax** [comment]
There is no fabric version.

**Comment by SadEPa0628** [comment]
I hope you can develop the Fabric version, which is needed for my server. Thank you very much

**Comment by henkelmax** [comment]
Won't happen.

**Comment by SadEPa0628** [comment]
![d0c05ce2afff4e680078e98cc533d241](https://github.com/henkelmax/ultimate-car-mod/assets/120295331/07a3084a-8eba-473b-a86d-cc0745ec9426)
![image](https://github.com/henkelmax/ultimate-car-mod/assets/120295331/d382b1ab-55d1-4e14-9c9a-0eaaa75160da)
