### ISSUE TITLE
[FEATURE REQUEST] New vehicle: Paver and Road Washer

### ISSUE THREAD

**Issue by Scwestbrook** [henkelmax/ultimate-car-mod#16]
**Is your feature request related to a problem? Please describe.**
Hi, I've been thinking, and I've decided that making roads by hand is just too hard. You have to lay down EVERY SINGLE BLOCK.
**Describe the solution you'd like**
The solution I would like is if you added a paver, because I would love it if you added a paver that you can input asphalt blocks into, and when you drive, it lays down asphalt and ramps when you go around. Also, as a side note, I'd also like it if you were to add a road washer vehicle, that you input water into, and washes the asphalt as you drive over it, and cars drive slower the longer it has been since you washed the road, to more closely simulate the real world, where grime and dust gather on roads.

**Describe alternatives you've considered**

**Additional context**

**Comment by henkelmax** [comment]
I already considered the Paver, but it would not fit into the current style of the mod, as it needs to be way bigger than every other car.

**Comment by Scwestbrook** [comment]
Thanks!

**Comment by henkelmax** [comment]
What would the purpose be?

**Comment by Scwestbrook** [comment]
The purpose would be to make cars move faster on roads if they had been cleaned recently, and I was thinking of both it and the paver as transporter-size vehicles rather then large ones.

**Comment by Scwestbrook** [comment]
Also, this mod seems to be about being realistic, unlike Mr crayfish's mod, where creative players don't need fuel, and I think that this would be nice.
