### ISSUE TITLE
How do I get rid of the bio diesel which incidentally placed on the ground?

### ISSUE THREAD

**Issue by neesonqk** [henkelmax/ultimate-car-mod#161]
**Bug description**
Playing in creative mode, incidentally, I placed the bio diesel bucket on the ground, it become liquid like a water block, but not like a water block, I could no longer get rid of it or destroy it anymore.  

**Steps to reproduce the issue**
1. Hit "E" to open items, choose "Car" menu.
2. Select "Bio Diesel Bucket" and put in hand
3. Place it on the ground just like placing other blocks.
4. It becomes a liquid status and can no longer been destroyed. 

**Expected behavior**
Should be able to destroyed.

**Versions**
- Minecraft version: 1.20.1
- Mod loader: Forge
- Mod loader version: 47.2.0
- Mod version: car-forge-1.20.1-1.0.12.jar

**Screenshots (Optional)**
<img width="1675" alt="Screenshot 2023-12-21 231934" src="https://github.com/henkelmax/ultimate-car-mod/assets/7279067/36c860ea-dbbf-493b-a82d-241460d81466">

**Comment by henkelmax** [comment]
https://github.com/henkelmax/ultimate-car-mod/assets/13237524/1b86072e-0055-4b84-a3b0-73b15a17d6ff
