### ISSUE TITLE
Locked out with both car keys in car inventory

### ISSUE THREAD

**Issue by Piktor99** [henkelmax/ultimate-car-mod#164]
You can easily get locked out of your car with both car keys still in the car's inventory.

Sit down in your car, pick up one of the keys while sitting in the car.
Right click with it to lock the car.
Open the car's inventory to put it back.
Step out of your car.

Now you have a car which you can't use with both of its keys inside.

![2024-01-29_22 05 22](https://github.com/henkelmax/ultimate-car-mod/assets/35896210/44b4c7d3-d2a5-4f08-ab98-ffc17a52c5cb)

**Comment by henkelmax** [comment]
Thanks for reporting this issue!
