### ISSUE TITLE
Car entity causes the connection lost

### ISSUE THREAD

**Issue by INF32768** [henkelmax/ultimate-car-mod#165]
### Bug description

In the server, players around the car (except for the server owner) will lose connection, and the game says :"Internal Exception: io.netty.handler.codec.DecoderException: Unknown serializer type x" (x will vary depending on the type of the car)

### Minecraft version

1.20.2

### Mod version

1.20.2-1.0.11

### Mod loader and version

Neoforge 20.2.86

### Steps to reproduce

1.Enter a world and open to LAN
2.Let another player connect
3.Spawn a car with the command "/summon car:car"
4.The error happened: Players who joined the server lost their connection

### Expected behavior

Players will not lose connection

### Log files

https://gist.github.com/INF32768/0adfba7d1ec71b1184f45b3ea5e77147

### Screenshots

Server owner:![2024-02-18_17 03 08](https://github.com/henkelmax/ultimate-car-mod/assets/119732966/19a251bf-6d4f-487f-a59e-afabb8d695de)
![2024-02-18_17 03 19](https://github.com/henkelmax/ultimate-car-mod/assets/119732966/09f59caf-8eb0-4c8d-88b5-193f60dd58e8)
![2024-02-18_17 03 42](https://github.com/henkelmax/ultimate-car-mod/assets/119732966/5fa1b5cd-d3e3-4c54-91ca-3d9cb65705be)
Players who joined the server:![Screenshot_20240218_170331_com tungsten fcl](https://github.com/henkelmax/ultimate-car-mod/assets/119732966/222099e3-0008-41a7-984e-fcbac7f9a562)

**Comment by henkelmax** [comment]
Minecraft 1.20.2 is no longer supported. Either use 1.20.1 or update to 1.20.4.
