### ISSUE TITLE
ultimate car mod 1.20.1 dont get power from immersive engineering 

### ISSUE THREAD

**Issue by FINK89i** [henkelmax/ultimate-car-mod#166]
### Bug description

hello i was playng on my world end i decided to start making bio disel so father i have made the oil extractor end the blasti furnace i have connected them to the LV of immersive engineering but it didnt work no power 

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.15

### Mod loader and version

forge 47.2.20

### Steps to reproduce

build end place a machine then put the object that it has to proces then connect it to immersive engineering power  

### Expected behavior

afther that it should work just fine whit the power from another mod

### Log files

https://gist.github.com/FINK89i/abe7648999db5d80942303e6234b3da3

**Comment by henkelmax** [comment]
Immersive Engineering does not use RF.
