### ISSUE TITLE
develope a forge 1.20.4 version

### ISSUE THREAD

**Issue by SeboBearBB** [henkelmax/ultimate-car-mod#168]
### Bug description

I need a 1.20.4 version of this mod to update my world, but I don't see one. I see that you did develop a neoforge version, so I think it is easy for you to make a forge version as these modloaders are very similar. My friends also need this forge version for their multiplayer server, so this would be really helpful.

### Minecraft version

1.20.4

### Mod version

1.20.2-1.0.11

### Mod loader and version

Forge 49.0.39

### Steps to reproduce

There is no forge version for 1.20.4. That is the issue.

### Expected behavior

I expect a forge version for 1.20.4, because it has already been a while, and there is a neoforge version.

### Log files

ok

### Screenshots

![image_2024-04-08_223059485](https://github.com/henkelmax/ultimate-car-mod/assets/166470133/e8f374cc-cd79-48ab-9ed6-66505f20508a)

**Comment by henkelmax** [comment]
There will only be NeoForge from now on.
