### ISSUE TITLE
Fuel from other mods

### ISSUE THREAD

**Issue by plunginghornets** [henkelmax/ultimate-car-mod#17]
I would like to use this mod in a pack, but there are already several ways to create diesel and biodiesel in the pack. Would it be possible to add compatibility with mods like Immersive Engineering or Pneumaticraft?

**Comment by henkelmax** [comment]
Just add the fluid id to the config.

**Comment by plunginghornets** [comment]
Damn. I jumped the gun assuming you hadn't already done this. Thank you!

**Comment by Patrick1417** [comment]
> Just add the fluid id to the config.

Could you please explain this in detail to me? 
Im using Immersive Engineering and i would like to use the Bio Diesel from your mod with the Immerserive Engineering Diesel Generator for example. Is this possible? 
I can fill your Bio Diesel into the Tank from the other mod, but it doesent work with the generator. Thank you.

**Comment by henkelmax** [comment]
You are right, the generator was missing in the config. This should be fixed in the latest version.
