### ISSUE TITLE
How to delete /cardemo vehicle please !!!

### ISSUE THREAD

**Issue by JLSkyzer** [henkelmax/ultimate-car-mod#170]
### Bug description

just do cardemo but how despawn

### Minecraft version

1.20.1

### Mod version

last 1.20.1

### Mod loader and version

Forge 47.2.10

### Steps to reproduce

JUST DO THE COMMAND AND HOW DESPAWN NOW

### Expected behavior

?

### Log files

Not needed

**Comment by JLSkyzer** [comment]
![image](https://github.com/henkelmax/ultimate-car-mod/assets/60830349/ddcbc2d3-0a2e-459b-add9-67b70effa9cb)

**Comment by henkelmax** [comment]
just use the `/kill` command with a selector for cars in a specific range.
Should look something like `/kill @e[type=car:car,range=...]`

**Comment by JLSkyzer** [comment]
ok thx
