### ISSUE TITLE
Botany Pots does not Recognize Canola Seeds as a Proper Seed

### ISSUE THREAD

**Issue by Mick0604** [henkelmax/ultimate-car-mod#173]
### Bug description

you cannot put canola seeds in botany pots. tried to make a datapack for it but was having a hard time. was wondering if i could get some help or if you knew any more information than i did. 

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.17

### Mod loader and version

Forge 47.2.17

### Steps to reproduce

put item in botany pot

### Expected behavior

item grows inside botany pot 

### Log files

none

**Comment by henkelmax** [comment]
I think pots don't generally accept any seed. You need to add it using a datapack: https://github.com/Darkhax-Minecraft/BotanyPots/wiki/Datapack-Information
