### ISSUE TITLE
Ultimate Car/Plane Mod crashing when launching

### ISSUE THREAD

**Issue by KRUTIKOVARTEM2009** [henkelmax/ultimate-car-mod#176]
### Bug description

When launching Ultimate Car Mod and its sister mod, Ultimate Plane Mod, the game crashes. With Neoforge. Can you make a Forge version?

### Minecraft version

1.21.1

### Mod version

car: 1.21.1-1.0.24 plane: 1.21.1-1.0.9

### Mod loader and version

NeoForge 21.1.11/21.1.35 (latest supported on my launcher is 21.1.23)

### Steps to reproduce

1. Launch the version where the mod is. (Neoforge)
2. See the error. Rinse and repeat ad nauseam.

### Expected behavior

The game should launch and run normally with the mods.

### Log files

https://gist.github.com/KRUTIKOVARTEM2009/09c930c7bedaf0f883d3cfacd5cb8e67

**Comment by henkelmax** [comment]
Works perfectly fine with the latest NeoForge and mod versions.

![image](https://github.com/user-attachments/assets/5086e919-fe87-43de-9b20-4a6df0a54a8d)

**Comment by KRUTIKOVARTEM2009** [comment]
Unfortunately, I have trouble with the mod loader itself, it doesn't launch and sends me an error message. Mods are fine
