### ISSUE TITLE
Cannot Transfer Ethanol To The Backmix Reactor

### ISSUE THREAD

**Issue by playerok202** [henkelmax/ultimate-car-mod#177]
### Bug description

Cannot Transfer Ethanol To The Backmix Reactor, I have Nuclear mod

### Minecraft version

1.12.2

### Mod version

1.12.2-1.2.12

### Mod loader and version

Forge 1.12.2 - 14.23.5.2860

### Steps to reproduce

![2024-09-30_20 04 06_2](https://github.com/user-attachments/assets/2e766030-0bc6-46e2-b548-b5ae10041f8b)

### Log files

https://gist.github.com/

**Comment by henkelmax** [comment]
This version is not supported anymore. Only 1.19.2, 1.20.1 and 1.21.1 are supported.
