### ISSUE TITLE
The car leans over even though I'm not doing anything.

### ISSUE THREAD

**Issue by miku1881** [henkelmax/ultimate-car-mod#178]
### Bug description

I'm using the Ultimate Car Mod in 1.20.1 multiplayer, and for some reason my car is leaning over after a few minutes of getting out.　Is there any way to fix this?　I've had a friend try it and the same thing is happening.

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.32

### Mod loader and version

Forge47.3.11

### Steps to reproduce

1. craft car
2. ride car
3. got out of the car
4. The car tipped over in a few minutes.

### Log files

https://gist.github.com/miku1881/428a125a6cde25a3deff0ee375d25f19

### Screenshots

![2024-10-26_10 47 05](https://github.com/user-attachments/assets/185523ff-8257-4380-ab8d-43a75a45556f)

**Comment by henkelmax** [comment]
Does that happen without any other mods?

**Comment by miku1881** [comment]
![2024-10-27_19 15 24](https://github.com/user-attachments/assets/cdf168cc-d1c9-49b2-8a20-cc4105e3d6d1)

The same thing happened even after removing other mods.

**Comment by henkelmax** [comment]
Can you send me your logs of this session?

**Comment by miku1881** [comment]
here you are 

https://gist.github.com/miku1881/ed9927805ddfde883090fc4fbd659659

**Comment by henkelmax** [comment]
I also need the server logs

**Comment by miku1881** [comment]
here you are

https://gist.github.com/miku1881/1b888d15c48c30d46f3a2d43b664a31c

**Comment by henkelmax** [comment]
We don't support hybrid servers.

**Comment by kronysan** [comment]
Did you manage to fix the problem or will they never fix it?

**Comment by miku1881** [comment]
There was a problem with the server wrapper.It was fixed by changing the server wrapper.

**Comment by kronysan** [comment]
you changed mohist for another one, which one was it? is that what you mean?

**Comment by miku1881** [comment]
I changed it to something different from mohist

**Comment by miku1881** [comment]
The name of that server wrapper is ketting launcher

**Comment by kronysan** [comment]
is kettin working well?

**Comment by kronysan** [comment]
I will give it a try thank you very much for the help
