### ISSUE TITLE
Middle Edge Double Line

### ISSUE THREAD

**Issue by ChrisLTheNerd** [henkelmax/ultimate-car-mod#18]
**Is your feature request related to a problem? Please describe.**
Every time I want to make a highway it's hard to deal with the lack of double line corners.

**Describe the solution you'd like**
I think that there should be a double line corners just like the middle edge lines. 

**Describe alternatives you've considered**

**Additional context**
![middle edge double line](https://user-images.githubusercontent.com/50182206/103307012-00813580-49dd-11eb-8355-956df8250b29.png)

**Comment by henkelmax** [comment]
Thank you for your suggestion. It should be up on CurseForge in a few minutes.
