### ISSUE TITLE
Crash Barrier Corners

### ISSUE THREAD

**Issue by ChrisLTheNerd** [henkelmax/ultimate-car-mod#19]
**Is your feature request related to a problem? Please describe.**
It's kind of frustrating when I'm building a road and the crash barriers leave gaps on the corners of blocks. 

**Describe the solution you'd like**
There should be crash barrier corners and inverted crash barrier corners. There should also be inverted crash barrier which are like the normal ones but they are further back on the block and they would match with the inverted crash barrier corners.

**Describe alternatives you've considered**

**Additional context**
![Crash_Barrier_Corner](https://user-images.githubusercontent.com/50182206/103307087-39210f00-49dd-11eb-94dc-20b5348598a6.png)
![Crash_Barrier_Inverted_Corner](https://user-images.githubusercontent.com/50182206/103307091-3b836900-49dd-11eb-8e2e-eead9e7df958.png)
![Inverted_Crash_Barrier](https://user-images.githubusercontent.com/50182206/103307604-7a65ee80-49de-11eb-8727-244b7e5c1a3c.png)

**Comment by henkelmax** [comment]
Thank you for your suggestion!
