### ISSUE TITLE
Gas station GUI slot

### ISSUE THREAD

**Issue by Scwestbrook** [henkelmax/ultimate-car-mod#20]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/car/faq)!**
What is the first slot in the gas station GUI for?

**Comment by henkelmax** [comment]
If you sneak and right click the gas station, it opens an admin GUI, where you can set an item and a fluid amount (You have to place the gas station yourself to access it). 
The slot you asked for is the payment slot. The thing next to the slot shows you how many fuel you get for this item.

**Comment by Scwestbrook** [comment]
Thanks! Also, who can access the admin GUI? I think only the person who placed it should be allowed to.

**Comment by henkelmax** [comment]
Exactly. But if you are OP on your server you can also access it.

**Comment by Scwestbrook** [comment]
Great! I wanted to do this on my server, but I was worried about people removing the price from my gas
