### ISSUE TITLE
Car is missing

### ISSUE THREAD

**Issue by Martin20047** [henkelmax/ultimate-car-mod#22]
Hey! (sorry  for my  bad  english)

I just  download ultimate Car mod in 1.12.2 in his last version on curseforge,  in the game all the machines and the road part are here,  but all the car part is missing, The Car entity itself is missing. I don't know if the mod depend on an other mod than the one in curse forge but its apparently don't work for me.

![2021-01-09_17 38 57](https://user-images.githubusercontent.com/26878570/104103304-9e101b00-52a1-11eb-820d-7b0c8f3ffad2.png)

**Comment by henkelmax** [comment]
Which version of the mod are you using?

**Comment by Martin20047** [comment]
Ultimate Car Mod 1.2.12
and i also try with
Ultimate Car Mod 1.2.11

**Comment by henkelmax** [comment]
What is the command you used to spawn it?

**Comment by Martin20047** [comment]
I try /summon Ultimate_car_mod:car ~ ~ ~2

**Comment by henkelmax** [comment]
That is completely wrong. The mod ID is `car`.

**Comment by Martin20047** [comment]
oh ok, but the item for creating the car still missing

**Comment by henkelmax** [comment]
Clearly you haven't read the wiki or the FAQ.

**Comment by Martin20047** [comment]
Oh ok there not bug fix for 1.12.2 versions. Thank you anyways

**Comment by henkelmax** [comment]
This is not a bug!
