### ISSUE TITLE
Parking Meter

### ISSUE THREAD

**Issue by Scwestbrook** [henkelmax/ultimate-car-mod#23]
**Is your feature request related to a problem? Please describe.**
Yes, everyone is taking spots on my server, and it gets really crowded, and annoying.

**Describe the solution you'd like**
I would like for there to be a parking meter block, where you can select a range and pay for a set amount of time (prices changeable in config). If you don't pay, or stop the engine in the spot before you pay, you can't move until you a) pay a set amount of money, or an server op comes along and lets you leave (For ops, if they sneak-right-click, they can change the price, and release cars that didn't pay.)

**Describe alternatives you've considered**
I can't really think of any other way, because this is a major problem on my server.

**Additional context**

**Comment by henkelmax** [comment]
This is a very niche feature. I don't think it is that useful for the most players. I also think it could get annoying very fast for players that log out of the game. Everything related to payment over time is very complicated, as the player can log out and the time still progresses.

**Comment by Scwestbrook** [comment]
OK, I'm making my own version anyway. Just wanted to make sure this wasn't going to be implemented. Also, most of my players made garages for their cars, it's just so they can't park on the street and get away with it. (I have a HUGE issue with this)

**Comment by Scwestbrook** [comment]
Also, this is mainly because people park in the middle of the road.
