### ISSUE TITLE
Canister Issue

### ISSUE THREAD

**Issue by Scwestbrook** [henkelmax/ultimate-car-mod#24]
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**
Done!

**Bug description**
When a player shift-right-clicks the gas station with a canister, it fills up without them paying.

**Steps to reproduce the issue**
Make a gas station with a cost (I'm using 900 emeralds to 1 mb of gas)
Shift-right-click it with a canister.
The canister has gas. You did not pay.

**Expected behavior**

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version 1.16.4
- Forge version 35.1.6
- Mod version

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
I don't think this is too much of an issue, since the canister is not the only way you can get the fuel without paying. You can extract fluid out of the gas station with the fluid extractor or with a bucket. This system is a little bit trust based, as you could always break the gas station and place it again.

**Comment by Scwestbrook** [comment]
I put my gas stations in the protected area of my server.

**Comment by Scwestbrook** [comment]
And setblock them constantly.
