### ISSUE TITLE
License plate not working

### ISSUE THREAD

**Issue by Scwestbrook** [henkelmax/ultimate-car-mod#26]
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**

**Bug description**
THe liscense plate doesn't work

**Steps to reproduce the issue**
1. Craft a car with a license plate and holder
2. See error
3. 
**Expected behavior**
The license plate should have shown.
**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version 1.16.5
- Forge version 31.6.09
- Mod version First 1.16.5 build

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.
Create, but I removed it and it still didn't work.
**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Have you read the wiki?

**Comment by Scwestbrook** [comment]
Yes, all it says is that there are custom car license plates.

**Comment by Scwestbrook** [comment]
I'm crafting with a named plate, it just doesn't show anything except the plate holder

**Comment by Scwestbrook** [comment]
It doesn't work on 1.16.4 either

**Comment by henkelmax** [comment]
Can you send a video of this?

**Comment by henkelmax** [comment]
ok

**Comment by Scwestbrook** [comment]
https://user-images.githubusercontent.com/74730069/106299996-ea58d600-6223-11eb-92b1-3ca73c5aa8a6.mp4

**Comment by Scwestbrook** [comment]
This is on my personal forge server. It did the same thing in singleplayer, though.

**Comment by henkelmax** [comment]
You have to sneak + right-click the car with the license plate.

**Comment by Scwestbrook** [comment]
Huh?????

**Comment by henkelmax** [comment]
After you built the car, right-click the car with the license plate.

**Comment by Scwestbrook** [comment]
Oh! Thanks!
