### ISSUE TITLE
fluid extractor using too much server

### ISSUE THREAD

**Issue by ink717** [henkelmax/ultimate-car-mod#27]
Recently I noticed a lagging issue in the server. Happen regardless of how many people online or whether the chunk was loaded and rendered. The fluid extractor always took the most computing allocation server. I removed all the fluid extractors across the map on a backup world and it gets fixed, with TPS and latency improving, 
A similar issue happens with gas stations and fluid pipes as well, but far less prominent than the fluid extractors.

![批注 2021-01-29 205340](https://user-images.githubusercontent.com/72815511/106343622-3c294c80-6274-11eb-9352-233d1508aaf0.png)

**Comment by henkelmax** [comment]
This is because the fluid extractor is a tileentity and all fluid pipes are no tileentity to save resources. But that has the side effect that the extractor tileentity in specific is very resource heavy. But compared to other mods pipes the fluid pipes themselves cause no lag at all.
