### ISSUE TITLE
 question

### ISSUE THREAD

**Issue by polarisow** [henkelmax/ultimate-car-mod#31]
How can I enable vehicle indestructibility and where exactly can I find the serverconfig file?

**Comment by henkelmax** [comment]
What do you mean with indestructibility? Read the FAQ.

**Comment by polarisow** [comment]
that the vehicle does not suffer any damage when hitting a block

**Comment by henkelmax** [comment]
This is not changeable.

**Comment by polarisow** [comment]
I read the FAQ but can't find the serverconfig file exactly where it is ?

**Comment by polarisow** [comment]
You cannot add an option in the configuration file so that the vehicle does not receive damage when it collides with another vehicle ?

**Comment by henkelmax** [comment]
> There are two types of configs. The config for the server side is located in your world folder in a subfolder called 'serverconfig'. The client side config is located in your '.minecraft' folder inside a subfolder called 'config'. Note that the client side and the server side config isn't the same. You can't put stuff from the server config into the client config. If you can't find the option you are looking for in the client config, try looking into the server config. There is always a server config, even if you are playing singleplayer, as it also uses an internal server.

Next time find it yourself!

**Comment by polarisow** [comment]
I have seen that before !!! but i can't see this file in the world folder

**Comment by polarisow** [comment]
I used modifications on one of the previously created worlds, I wanted to view the file but in the saves folder there is no file or serverconfig folder.

**Comment by polarisow** [comment]
???
