### ISSUE TITLE
Tractor&Harvester

### ISSUE THREAD

**Issue by polarisow** [henkelmax/ultimate-car-mod#32]
Can you make a tractor with "built-in" seeder for cereals, carrots, potatoes, bone meal, etc. and a combine harvester for mowing the above-mentioned products, of course without bone meal, which naturally serves as fertilizer?

**Comment by henkelmax** [comment]
Sorry, I am not planning on adding new vehicles.

**Comment by polarisow** [comment]
What are you planning then?

**Comment by henkelmax** [comment]
Nothing.
