### ISSUE TITLE
Fuel station not accepting biodiesel in Sevtech 

### ISSUE THREAD

**Issue by Kingace75** [henkelmax/ultimate-car-mod#33]
Been playing through Sevtech recently and came across this mod. Everything works fine but the final fuel product won't pump into the fuel station. I can't even bucket the fuel into it. I am aware Sevtech is running a fairly outdated version at this point but any help would be appreciated.

**Comment by henkelmax** [comment]
Please use the provided issue template.

**Comment by Kingace75** [comment]
I managed to fix the issue for anyone that may see this using Sev Tech but the "Bio Diesel" from the Ultimate Car mod unless you edit the config file will not work you have to use Immersive Engineering "Biodiesel".
