### ISSUE TITLE
How do I make methanol?

### ISSUE THREAD

**Issue by megwah** [henkelmax/ultimate-car-mod#36]
I've been following the Wiki and it says to use wood logs in the blast furnace to create methanol, however when I have done this in my game, nothing seems to happen, I have tried oak and spruce logs, wood and planks and still nothing. 

Please tell me where I'm going wrong!

**Comment by henkelmax** [comment]
Are you using the blast furnace of the car mod?

**Comment by megwah** [comment]
Yes I am

**Comment by henkelmax** [comment]
Can you send me a screenshot or a video of this?

**Comment by megwah** [comment]
I think I've fixed it, I restarted the game and disconnected a few items from the dynamo and it appears to be working now! thank you for your quick replies
