### ISSUE TITLE
Issues Using this mod Forge Server

### ISSUE THREAD

**Issue by AbdullahAhmed-hackintosh** [henkelmax/ultimate-car-mod#37]
Hi, I am having a lot of issues trying to place blocks in Forge Server. I have tested the Mod (Ultimate Car Mod) on a local world and everything works but when I join my forge server, it doesn't seem to allow me to place certain Blocks provided by the mod!

The Mod does allow me to put down some things like a 'Gas station' but does not allow me to put down the 'Workshop' and 'Parts workshop'

- Minecraft version: 1.16.5
- Forge version: forge-1.16.5-36.0.43
- Mod version: car-1.16.5-1.0.3

Other mods:
Simple Planes (Planes seems to have the same issue as Ultimate car mod) (And i also tested without this mod and with it)

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Plese send me a video of this issue!

**Comment by AbdullahAhmed-hackintosh** [comment]
https://user-images.githubusercontent.com/70412982/109812351-dc7fe180-7c23-11eb-93f4-adbb1da4e9c6.mp4



Hi, sorry for the late reply (was in school)! Here is the video

**Comment by henkelmax** [comment]
Does this also happen with vanilla blocks?
Looks like spawn protection for me.

**Comment by AbdullahAhmed-hackintosh** [comment]
Hi, No this does not happen with vanilla blocks

**Comment by AbdullahAhmed-hackintosh** [comment]
Yh i think there is some kind of 'lock'! but that does not explain why you can place some blocks from the mod but not others

**Comment by henkelmax** [comment]
Does this happen without any other mods installed?
Does this also happen if you go somewhere else?

**Comment by AbdullahAhmed-hackintosh** [comment]
Yes and Yes!

**Comment by henkelmax** [comment]
Can you test it with a fresh world?

**Comment by AbdullahAhmed-hackintosh** [comment]
Ok ill try now!

**Comment by AbdullahAhmed-hackintosh** [comment]
Yes i just tried now, EXACT same thing!

**Comment by henkelmax** [comment]
Are you using just forge on your server or some kind of modified version?

**Comment by AbdullahAhmed-hackintosh** [comment]
I am using Forge and not any modified version

**Comment by henkelmax** [comment]
Can you try a clean install without any config modifications?

**Comment by AbdullahAhmed-hackintosh** [comment]
Ok Ill try now

**Comment by AbdullahAhmed-hackintosh** [comment]
Yep! Having the EXACT same issues!!

**Comment by henkelmax** [comment]
I just tested it on my server and it works perfectly fine.
What's with your client? Does it have some other mods?

**Comment by AbdullahAhmed-hackintosh** [comment]
Sorry for making you worry that your GREAT mod had issues! I was being stupid and running Vanilla rather than forge jar file


Thank you for your help anyways!!
