### ISSUE TITLE
Gas container crash

### ISSUE THREAD

**Issue by GradiusLover2000** [henkelmax/ultimate-car-mod#4]
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**

**Bug description**
By holding shift then right clicking on a car with a fuel container in hand, it crashes the game immediately.  Self explanatory.

**Log files**
https://drive.google.com/file/d/12ZnPEbwTJNiyvPgvlRc2R5I9VKF7CYyE/view?usp=sharing

**Versions**
- Minecraft version 1.16.2
- Forge version 33.0.22+ (33.0.22 and 33.0.32 tested)
- Mod version 1.0.3

**Other mods**
Too many to list.  However, the crash report does not show any external mod classes in the classpath.  Might this be an optifine issue?

**Comment by henkelmax** [comment]
Unfortunately I am unable to reproduce this issue. Can you explain it in a little more detail?

**Comment by GradiusLover2000** [comment]
To replicate the issue as requested:

Summon a car with the command /summon car:car
Get a fuel container (the red box-like item with a tube) from the creative inventory (don't fill it or anything)
Hold shift to croutch.
Click on the car you summoned with the fuel container in your hand.

By doing this, my game crashes and gives the errors found in the log I already posted.  It seems to be tied to some sort of animation your mod attempts to play when I interact with the car with the fuel container.  Is there a deprecated interaction that still manages to find its way into the code?  Since I can see you can also refuel the car in its GUI.

**Comment by henkelmax** [comment]
Thanks for reporting this issue!
It should be fixed in the latest version.

**Comment by GradiusLover2000** [comment]
It is indeed, thanks a bunch!

**Comment by henkelmax** [comment]
No problem!
