### ISSUE TITLE
Car is not working

### ISSUE THREAD

**Issue by YoutubeCraft** [henkelmax/ultimate-car-mod#40]
Hi, I created and charged car with a fuel and it is not riding. How I can fix that?

**Comment by henkelmax** [comment]
You have to describe your problem in more detail.
Have you read the wiki?

**Comment by YoutubeCraft** [comment]
Yes, I have read the wiki.

**Comment by YoutubeCraft** [comment]
I press W and my car is not riding. And it is full of fuel.

**Comment by henkelmax** [comment]
Is the engine started?

**Comment by YoutubeCraft** [comment]
What engine?

**Comment by henkelmax** [comment]
You clearly haven't read the wiki.

**Comment by YoutubeCraft** [comment]
I read wiki now. How to start engine?

**Comment by henkelmax** [comment]
It is described in the wiki. So you still haven't read it!

**Comment by YoutubeCraft** [comment]
I did not notice the Vehicle Operation part of the wiki. I recognize the problem now. Thanks for help.
