### ISSUE TITLE
Add some new features 

### ISSUE THREAD

**Issue by AbdullahAhmed-hackintosh** [henkelmax/ultimate-car-mod#43]
Hi @henkelmax , Hope you are well during these hard times!

I was hoping you could add some new features to this mod such as:

Car/Truck Horns
Headlights and brake lights
Indicators
More Vehicle Bodies (Like Minibuses etc.)

I would just like to thank you for frequently updating this fantastic mod! Keep all your hard work up!

**Comment by henkelmax** [comment]
Currently, I have no plans on adding new content to this mod.
