### ISSUE TITLE
Issues with car mod

### ISSUE THREAD

**Issue by amandexspeed** [henkelmax/ultimate-car-mod#45]
**Bug description**
When I use optifine I have a bug is caused by troubles in get block alias, and , even without optifine, if you place 2 asphalt slabs together, making a block, we just receive 1 slab in drop.

**Steps to reproduce the issue**
1. Go to a especific part of the world
2. Run/Drive/Fly
3. The Games stops
4. Crashes by a Java.nullpointerexception

**Expected behavior**
When I put 2 slabs together I can have 2 slabs back.
Play my game without crash

**Log files**
[crash-2021-03-31_16.31.58-client.txt](https://github.com/henkelmax/ultimate-car-mod/files/6244444/crash-2021-03-31_16.31.58-client.txt)

**Versions**
- Minecraft version 1.16.5
- Forge version 36.1.2
- Mod version 1.0.5

**Screenshots (Optional)**

https://youtu.be/CxRJj6PWjR4

**Comment by amandexspeed** [comment]
If you want the lastest.log i can send

**Comment by henkelmax** [comment]
So this crash also happens without OptiFine?
Can you please send me the crash logs of the crash without OptiFine?

**Comment by henkelmax** [comment]
The slab bug should now be fixed.

**Comment by amandexspeed** [comment]
The bug that closes minecraft not.
But the slab bug yes

**Comment by henkelmax** [comment]
Then report this bug to the OptiFine issue tracker, please.

**Comment by amandexspeed** [comment]
But If you could check if the issue that closes minecraft can be solved by you I'll be gratefull

**Comment by amandexspeed** [comment]
No one talks in the optifine issue that i created in optifine issue tracker...

**Comment by henkelmax** [comment]
> But If you could check if the issue that closes minecraft can be solved by you I'll be gratefull

This is an OptiFine issue, I cant do much about it.


> No one talks in the optifine issue that i created in optifine issue tracker...

The OptiFine guys have much to do, it always takes a wile for them I guess.

**Comment by amandexspeed** [comment]
ok, thanks so
