### ISSUE TITLE
Unknown recipe serializer: Car:crafting_special_key

### ISSUE THREAD

**Issue by Atten007** [henkelmax/ultimate-car-mod#47]
Hi @henkelmax and hi @Aemande123,

I like your mod very, BUT it has a very nasty bug, the bug nets not join me the game. This is a screenshot of the bug after I tried to join the game:

![Bildschirmfoto 2021-05-02 um 10 45 01](https://user-images.githubusercontent.com/82451536/116807499-c0b98e80-ab33-11eb-9c2c-02e86be247e3.png)

If you can fix this, me and the other mod users would be very happy! I use mod version 1.0.4 and Minecraft version 1.16.5. Other mods I use with this mod are only world edit and the ultimate plane mod.

Sincerely yours,

Atten007😊

**Comment by henkelmax** [comment]
Please fill out the complete bug template

**Comment by Atten007** [comment]
And what is the complete bug template?

**Comment by henkelmax** [comment]
https://github.com/henkelmax/ultimate-car-mod/issues/new?assignees=henkelmax&labels=bug&template=bug_report.md&title=
