### ISSUE TITLE
Nasty bug in your nice Ultimate Car mod

### ISSUE THREAD

**Issue by Atten007** [henkelmax/ultimate-car-mod#48]
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**

**Bug description**

The bug is nasty, it lets me not join the game when I'm connecting with my server.

**Steps to reproduce the issue**
1. Open Minecraft
2. Click on "Multiplayer"
3. Go to "Add Server"
4. Type in "AttenCityJ.exaroton.me"
5. Try to join the server
6. It won't work because there's a unknown recipe serializer

**Expected behavior**

I expected that the mod works and I can play with cars, but then I couldn't join the game because there was the following error:

Unknown recipe Serializer for car: oil_mil (The bug happens with each item/block when I try to join the game)

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version 1.16.5
- Forge version 36.1.0
- Mod version 1.16.5 - 1.0.4

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

I only used world edit and ultimate plane mod with this mod.

**Screenshots (Optional)**
Screenshots of the issue.

![Bildschirmfoto 2021-05-02 um 10 45 01](https://user-images.githubusercontent.com/82451536/116811928-36315900-ab4c-11eb-8fa4-b45aed68ee48.png)

**Comment by henkelmax** [comment]
Please install the latest version and try it again.

**Comment by Atten007** [comment]
Ich habe gesehen, dass du ein Update veröffentlicht hast. Ich werde jetzt mal versuchen, deinen Mod (aktuelle Version) auf meinem Server laufen zu lassen. Ich schreibe in Deutsch zu dir, da ich gemerkt habe, dass du aus Deutschland kommst.

**Comment by Atten007** [comment]
Hat nicht geklappt, da steht: Unknown recipe serializer for: car: crafting_special_key. Könntest du das bitte beheben? Da würde ich mich sehr freuen (und die anderen Mod-User bestimmt auch).

**Comment by henkelmax** [comment]
I am not able to reproduce this issue. Does it work without any other mods installed?

**Comment by Atten007** [comment]
No, it doesn't work without any other mods installed. I can't provide the logs because there's not a entry in the log file.

**Comment by Atten007** [comment]
This time it shows: Unexpected serializer: car:blast_furnace

**Comment by Atten007** [comment]
Is it because I did not install forge on the client?

**Comment by henkelmax** [comment]
Of course you need to install the mod on the client! Which mod doesn't need to be installed on the client?

**Comment by Atten007** [comment]
Hallo Henkelmax,

der fiese Fehler in deinem Mod ist immer noch da, es wäre sehr schön, wenn du ihn beheben könntest mit der Mod-Version 1.16.5-1.0.10 oder 1.16.5-1.1.0, denn da würden ich und die anderen Mod-User, die diesen Mod auch verwenden und diesen fiesen Fehler haben sich sehr freuen.

LG Atten007

**Comment by henkelmax** [comment]
You still didn't provide the logs of your server and client.
You also didn't install forge on your client as far as I can tell.

**Comment by Atten007** [comment]
Hier ist die Log-Datei von meinem Exaroton-Server:

[05May2021 12:57:08.004] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.1.0, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
2	[05May2021 12:57:08.006] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 15.0.2 by Oracle Corporation
3	[05May2021 12:57:08.229] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
4	[05May2021 12:57:08.271] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/server/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=SERVER
5	[05May2021 12:57:09.033] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
6	[05May2021 12:57:12.445] [modloading-worker-1/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 36.1.0, for MC 1.16.5 with MCP 20210115.111550
7	[05May2021 12:57:12.446] [modloading-worker-1/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v36.1.0 Initialized
8	[05May2021 12:57:12.778] [modloading-worker-0/INFO] [com.sk89q.worldedit.forge.ForgeWorldEdit/]: WorldEdit for Forge (version 7.2.5+57d5ac9) is loaded
9	[05May2021 12:57:12.779] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [car] Starting version check at https://maxhenkel.de/update/car.json
10	[05May2021 12:57:13.026] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [car] Found status: UP_TO_DATE Current: 1.16.5-1.0.9 Target: null
11	[05May2021 12:57:13.026] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [plane] Starting version check at https://maxhenkel.de/update/plane.json
12	[05May2021 12:57:13.078] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [plane] Found status: AHEAD Current: 1.16.5-1.0.7 Target: null
13	[05May2021 12:57:13.078] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
14	[05May2021 12:57:13.722] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: UP_TO_DATE Current: 36.1.0 Target: null
15	[05May2021 12:57:19.915] [main/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
16	[05May2021 12:57:20.220] [main/WARN] [net.minecraft.command.Commands/]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
17	[05May2021 12:57:20.222] [main/WARN] [net.minecraft.command.Commands/]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
18	[05May2021 12:57:20.223] [main/WARN] [net.minecraft.command.Commands/]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
19	[05May2021 12:57:20.224] [main/WARN] [net.minecraft.command.Commands/]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
20	[05May2021 12:57:20.225] [main/WARN] [net.minecraft.command.Commands/]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
21	[05May2021 12:57:20.229] [main/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Default, bukkit, forge-1.16.5-36.1.0-universal.jar, car-1.16.5-1.0.9.jar, plane-1.16.5-1.0.7.jar, worldedit-mod-7.2.5-dist.jar
22	[05May2021 12:57:20.944] [Worker-Main-2/INFO] [net.minecraft.item.crafting.RecipeManager/]: Loaded 9 recipes
23	[05May2021 12:57:21.308] [Worker-Main-2/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 927 advancements
24	[05May2021 12:57:26.092] [main/WARN] [net.minecraftforge.fml.FMLWorldPersistenceHook/WP]: This world was saved with mod car version 1.16.5-1.0.8 and it is now at version 1.16.5-1.0.9, things may not work well
25	[05May2021 12:57:30.965] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Starting minecraft server version 1.16.5
26	[05May2021 12:57:30.966] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Loading properties
27	[05May2021 12:57:30.966] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Default game type: CREATIVE
28	[05May2021 12:57:30.966] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Generating keypair
29	[05May2021 12:57:31.007] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Starting Minecraft server on *:27374
30	[05May2021 12:57:31.022] [Server thread/INFO] [net.minecraft.network.NetworkSystem/]: Using epoll channel type
31	[05May2021 12:57:31.124] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Preparing level "world"
32	[05May2021 12:57:31.193] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Preparing start region for dimension minecraft:overworld
33	[05May2021 12:57:31.885] [Server thread/INFO] [net.minecraft.world.chunk.listener.LoggingChunkStatusListener/]: Preparing spawn area: 0%
34	[05May2021 12:57:31.885] [Server thread/INFO] [net.minecraft.world.chunk.listener.LoggingChunkStatusListener/]: Preparing spawn area: 0%
35	[05May2021 12:57:32.199] [Server thread/INFO] [net.minecraft.world.chunk.listener.LoggingChunkStatusListener/]: Preparing spawn area: 58%
36	[05May2021 12:57:32.311] [Server thread/INFO] [net.minecraft.world.chunk.listener.LoggingChunkStatusListener/]: Time elapsed: 1118 ms
37	[05May2021 12:57:32.312] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Done (1.216s)! For help, type "help"
38	[05May2021 12:57:32.313] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Starting GS4 status listener
39	[05May2021 12:57:32.315] [Server thread/INFO] [net.minecraft.network.rcon.RConThread/]: Thread Query Listener started
40	[05May2021 12:57:32.316] [Query Listener #1/INFO] [net.minecraft.network.rcon.QueryThread/]: Query running on 0.0.0.0:9898
41	[05May2021 12:57:32.548] [Netty Epoll Server IO #1/INFO] [net.minecraftforge.fml.server.ServerLifecycleHooks/SERVERHOOKS]: Disconnecting Player (server is still starting): Server is still starting! Please wait before reconnecting.
42	[05May2021 12:57:32.639] [Server thread/INFO] [com.sk89q.worldedit.extension.platform.PlatformManager/]: Got request to register class com.sk89q.worldedit.forge.ForgePlatform with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@23e1d43d]
43	[05May2021 12:57:33.145] [Server thread/INFO] [com.sk89q.worldedit.extension.platform.PlatformCommandManager/]: Registering commands with com.sk89q.worldedit.forge.ForgePlatform
44	[05May2021 12:57:42.461] [User Authenticator #1/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: UUID of player Atten007 is e4b1f76d-5865-40fa-8ca8-0419b88f701c
45	[05May2021 12:57:42.624] [Server thread/INFO] [net.minecraftforge.common.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@65014a87
46	[05May2021 12:57:42.638] [Server thread/INFO] [net.minecraft.server.management.PlayerList/]: Atten007[/176.198.119.0:50908] logged in with entity id 59 at (1363.4271951413034, 69.0, -277.46329276695747)
47	[05May2021 12:57:42.667] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: [Owner] Atten007 joined the game
48	[05May2021 12:57:42.934] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Atten007 lost connection: Disconnected
49	[05May2021 12:57:42.934] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: [Owner] Atten007 left the game
50	[05May2021 12:57:55.732] [User Authenticator #2/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: UUID of player YoutubeRedDevil is fb0f475d-948a-409f-a39f-c0e0b3aedf81
51	[05May2021 12:57:55.837] [Server thread/INFO] [net.minecraftforge.common.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@683e1348
52	[05May2021 12:57:55.844] [Server thread/INFO] [net.minecraft.server.management.PlayerList/]: YoutubeRedDevil[/77.4.75.181:65011] logged in with entity id 76 at (1396.1480672439263, 70.0, -366.919963790898)
53	[05May2021 12:57:55.860] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: YoutubeRedDevil joined the game
54	[05May2021 12:57:55.954] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: YoutubeRedDevil lost connection: Disconnected
55	[05May2021 12:57:55.955] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: YoutubeRedDevil left the game
56	[05May2021 12:58:36.254] [User Authenticator #3/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: UUID of player Atten007 is e4b1f76d-5865-40fa-8ca8-0419b88f701c
57	[05May2021 12:58:36.331] [Server thread/INFO] [net.minecraftforge.common.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@7b7930fc
58	[05May2021 12:58:36.336] [Server thread/INFO] [net.minecraft.server.management.PlayerList/]: Atten007[/176.198.119.0:50952] logged in with entity id 77 at (1363.4271951413034, 69.0, -277.46329276695747)
59	[05May2021 12:58:36.346] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: [Owner] Atten007 joined the game
60	[05May2021 12:58:36.577] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Atten007 lost connection: Disconnected
61	[05May2021 12:58:36.578] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: [Owner] Atten007 left the game
62	[05May2021 13:00:36.423] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Stopping the server
63	[05May2021 13:00:36.471] [Server thread/INFO] [com.sk89q.worldedit.extension.platform.PlatformManager/]: Unregistering com.sk89q.worldedit.forge.ForgePlatform from WorldEdit
64	[05May2021 13:00:36.477] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
65	[05May2021 13:00:36.478] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
66	[05May2021 13:00:36.478] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
67	[05May2021 13:00:36.478] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
68	[05May2021 13:00:37.265] [Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (world): All chunks are saved
69	[05May2021 13:00:37.266] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
70	[05May2021 13:00:37.267] [Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
71	[05May2021 13:00:37.267] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
72	[05May2021 13:00:37.268] [Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
73	[05May2021 13:00:37.282] [Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (world): All chunks are saved
74	[05May2021 13:00:37.284] [Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
75	[05May2021 13:00:37.284] [Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
76	[05May2021 13:00:37.578] [Server thread/INFO] [net.minecraft.network.rcon.RConThread/]: Thread Query Listener stopped
77

**Comment by Atten007** [comment]
Und ich habe Forge auch auf dem Client installiert und es damit probiert, aber damit hat es auch nicht geklappt :(

**Comment by Atten007** [comment]
Und hier noch ein Screenshot, was angezeigt wird, wenn man auf den Server drauf will:

![Bildschirmfoto 2021-05-05 um 12 57 50](https://user-images.githubusercontent.com/82451536/117132987-f19ffa80-ada3-11eb-8d4f-ac3c7353a43e.png)

**Comment by henkelmax** [comment]
Please use github gist for logs

**Comment by Atten007** [comment]
Ok, ich werde es zukünftig für Logs benutzen.

**Comment by henkelmax** [comment]
I need the logs with github gist. It is not readable like this.

**Comment by Atten007** [comment]
Sorry, für die späte Rückmeldung. Hier ist der Link zum Logfile auf Github Gist:

https://gist.github.com/Atten007/73281aa391ba1848a2b4bb32a6808e5e

**Comment by henkelmax** [comment]
Does it happen without any additional mods installed?

**Comment by Atten007** [comment]
Ja, es ist passiert, ohne dass andere Mods installiert waren.

**Comment by Atten007** [comment]
Ja, ich bin mir da ganz sicher, ich schicke dir die Logs vom Client später, ok?

**Comment by henkelmax** [comment]
You sent me server logs. I need client logs.

As I already said. The bug is only occuring for you! I am using the mod right now on my server and it works fine.

**Comment by Atten007** [comment]
Ich werde mal testen, ob ich mit dem Forge-Client auf die Arten City komme, dann schicke ich dir die Client-Logs, ok? LG Atten007

**Comment by henkelmax** [comment]
You ALWAYS need to have the mod installed on the client and the server!
I have no clue what "Arten City" is

**Comment by Atten007** [comment]
Sorry, das war die Autokorrektur.

**Comment by Atten007** [comment]
Jetzt funktioniert es bei mir! Ich musste nur die Mods auf dem Client installieren.

**Comment by henkelmax** [comment]
Thank you for wasting my time!
That's what I told you a week ago!

**Comment by Atten007** [comment]
Sorry für die Zeitverschwendung (ich entschuldige mich auch dafür), ich habe den Ordner mit den Mods aber nicht gefunden. Jetzt läuft alles ganz flüssig ohne Probleme. Ich werde so etwas mit Zeitverschwendung nie mehr machen und befolge beim nächsten mal **direkt**, was du sagst, damit sowas nicht nochmal vorkommt. LG Atten007😊
