### ISSUE TITLE
I have problem with the mod is not working when i place any mod block in game

### ISSUE THREAD

**Issue by n0uremam** [henkelmax/ultimate-car-mod#50]
I have a problem with the mod is not working when i place any mod block in-game

here some examples please help

https://user-images.githubusercontent.com/84910254/119818953-20674780-bef0-11eb-8548-9c495e6478a9.mp4
![Base Profile Screenshot 2021 05 27 - 13 30 30 25](https://user-images.githubusercontent.com/84910254/119819019-3248ea80-bef0-11eb-88b5-f529fa03977b.png)

**Comment by henkelmax** [comment]
Please fill out the bug template.
Also make sure you have no other mods and plugins installed.

**Comment by n0uremam** [comment]
how?

**Comment by n0uremam** [comment]
how?

**Comment by henkelmax** [comment]
Just fill out the template that is provided when creating a issue

**Comment by n0uremam** [comment]
can u help me with that because this is the first time to use mods
