### ISSUE TITLE
I have problem with the mod is not working when i place any mod block in game

### ISSUE THREAD

**Issue by n0uremam** [henkelmax/ultimate-car-mod#51]
**Bug description**
I have a problem with the mod is not working when I place any mod block in-game

**Log files**
[log.txt](https://github.com/henkelmax/ultimate-car-mod/files/6553793/log.txt)

**Versions**
- Minecraft version 1.16.5
- Forge version 36.1.24
- Mod version 1.16.5-1.0.10

**Other mods**
None

**Screenshots (Optional)**

https://user-images.githubusercontent.com/84910254/119820269-9324f280-bef1-11eb-86ee-2d4b78848c53.mp4

![20210527132558_1](https://user-images.githubusercontent.com/84910254/119820326-a2a43b80-bef1-11eb-8d4a-44330e979b4f.jpg)

**Comment by henkelmax** [comment]
Please add the full logs. The logs you sent are incomplete.

**Comment by n0uremam** [comment]
I am using singleplayer 

[log.txt](https://github.com/henkelmax/ultimate-car-mod/files/6553787/log.txt)

**Comment by henkelmax** [comment]
Does it only happen with the workshop or with other blocks of the mod?

Can you try placing the blocks on a different location and in a newly generated world?

**Comment by n0uremam** [comment]
I tried on another world and with all car blocks

**Comment by henkelmax** [comment]
That's weird... Can you try a fresh installation of minecraft?

**Comment by n0uremam** [comment]
ok I will try and return u back

**Comment by n0uremam** [comment]
It worked after fresh installation of minecraft

**Comment by n0uremam** [comment]
but i found the reason of the bug

**Comment by n0uremam** [comment]
i will rec and post it here
