### ISSUE TITLE
How To remove all cars on the map

### ISSUE THREAD

**Issue by n0uremam** [henkelmax/ultimate-car-mod#52]
**Bug description**
How To remove all cars on the map because I spwam by wrong democars 

**Expected behavior**
To remove all cars on the map

**Versions**
- Minecraft version 1.16.5
- Forge version 36.1.24
- Mod version 1.16.5-1.0.17

**Other mods**
None

**Screenshots
![20210611184717_1](https://user-images.githubusercontent.com/84910254/121722421-b9e44b00-cae5-11eb-9763-3540d58b7b27.jpg)

**Comment by henkelmax** [comment]
`/kill @e[type=car:car]`

**Comment by n0uremam** [comment]
> 
> 
> `/kill @e[type=car:car]`

thx it worked
