### ISSUE TITLE
How to change the arrow selected in-game (Painter Tool)

### ISSUE THREAD

**Issue by n0uremam** [henkelmax/ultimate-car-mod#53]
Bug description
How to change the arrow selected in-game (Painter Tool)

Expected behavior
To know how to change the selected by the game tool

Versions

    Minecraft version 1.16.5
    Forge version 36.1.24
    Mod version 1.16.5-1.0.17

Other mods
None.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/84910254/121772997-66bbd800-cb79-11eb-8cf1-f0ea3db21262.PNG)
![11](https://user-images.githubusercontent.com/84910254/121773003-6f141300-cb79-11eb-878d-ce495fd4cf25.png)

**Comment by henkelmax** [comment]
https://modrepo.de/minecraft/car/wiki?t=road_construction
