### ISSUE TITLE
Other fuels not working on car

### ISSUE THREAD

**Issue by TqLxQuanZ** [henkelmax/ultimate-car-mod#54]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/car/faq)!**

Hello, I've modified the car-server.toml and managed to get the fuels into the gas_station (ImmersiveEngineering Gasoline), but whenever I try to refuel the car it just doesn't work, it does detect the car nearby.
What I did is adding the other mod fluids into the #car:gas_station tag.

As for the car, I managed to empty the fuel by driving around (Is there other way to empty fuel by clicking?) But I just can't get to use the other mod's fluid to fuel the car, any idea what goes wrong?

**Comment by henkelmax** [comment]
You need to add the fluid to the fuel config. Adding it to the gas station only allows the fluid to go into the gas station.
