### ISSUE TITLE
1.16 : There is no "car_step_height" option

### ISSUE THREAD

**Issue by ExDomino** [henkelmax/ultimate-car-mod#58]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/car/faq)!**

Hello, in 1.12, the config "car_step_height" was useful to make cars able to step a full block. This config seems to be gone in 1.16. How to make cars able to jump a full block please? Thank you in advance!

**Comment by henkelmax** [comment]
This option was removed in favor to SUVs
