### ISSUE TITLE
Gas stations permanently break worlds

### ISSUE THREAD

**Issue by imagelesskink** [henkelmax/ultimate-car-mod#61]
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**

**Bug description**
After closing out of the gas station GUI, I'm unable to open any more GUIs. Afterwards, if I exit the world, it will never load again, it gets stuck eternally at 100%.

**Steps to reproduce the issue**
1. Right click on Gas station
2. Close GUI
3. Try to open a chest or re-open the gas station gui, then leave world
4. Try to enter the world again and wait for a couple hours before giving up

**Expected behavior**
Normal behavior.

**Log files**
It's long, but I'm including the entire log file since minecraft didn't crash with an error.
[latest.log](https://github.com/henkelmax/ultimate-car-mod/files/7024386/latest.log)

**Versions**
- Minecraft version: 1.17.1
- Forge version: 37.0.41
- Mod version: 1.17.1 - 1.0.1

**Other mods**
I've got lots, but the same problem happened after I removed them all.

**Comment by henkelmax** [comment]
Thank you for reporting this issue. It should be fixed in the next version.

**Comment by imagelesskink** [comment]
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**

**Bug description**
A clear and concise description of what the bug is.

**Steps to reproduce the issue**
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- 1.17.1
- 37.0.44
- 1.17.1-1.0.2

**Other mods**
Happens with no other mods installed

**Screenshots (Optional)**
Screenshots of the issue.
