### ISSUE TITLE
Gas Stations still permanently break worlds

### ISSUE THREAD

**Issue by imagelesskink** [henkelmax/ultimate-car-mod#62]
Gas stations work now and you can still open GUIs after using one, but once you close the world it won't open again unless you delete the gas station with Amulet.

**Comment by henkelmax** [comment]
Please fill out the complete bug template.

Does this also happen for newly created worlds?

**Comment by imagelesskink** [comment]
It still happens in newly created worlds.

**Comment by henkelmax** [comment]
Please fill out the complete bug template including logs.
