### ISSUE TITLE
Italian Translation (1.17.1-1.0.5)

### ISSUE THREAD

**Issue by DarkMysteryGG** [henkelmax/ultimate-car-mod#65]
Hey! I made this translation to Italian language, about 3 hours of work. This is the first version so if there is any error or something else i will correct all of them.
[it_it.txt](https://github.com/henkelmax/ultimate-car-mod/files/7190415/it_it.txt)

This is the .txt file, unfortunately github doesn't support .json file directly but this should be the same.

**Comment by henkelmax** [comment]
Thank you very much! It will be available on CurseForge in a few minutes.

**Comment by DarkMysteryGG** [comment]
Hey there! I checked that everything in the translation was okay and there were some errors so I corrected them. I advise you to reload the 1.0.7 version on CurseForg
[it_it.txt](https://github.com/henkelmax/ultimate-car-mod/files/7190687/it_it.txt)
e!

**Comment by DarkMysteryGG** [comment]
The Italian translation doesn't work in the mod!😢

**Comment by henkelmax** [comment]
![image](https://user-images.githubusercontent.com/13237524/133933561-97175a5f-2bb0-4554-8ec0-a74bc8c8dfa3.png)
You had an extra `"` in the json.

**Comment by DarkMysteryGG** [comment]
Ok, now it works👍. If I have any update i'll put it here.

**Comment by DarkMysteryGG** [comment]
Ok, i did it. I checked that everything was fine and correct, also in minecraft and it's now totally corrected. Sorry for all this messages and the inconvenience😅. Anyway here is the last correction:
[it_it.txt](https://github.com/henkelmax/ultimate-car-mod/files/7192570/it_it.txt)
As always, for any updates i'll put it here😉

**Comment by henkelmax** [comment]
Next time, please make sure everything is correct before sending me a translation.
