### ISSUE TITLE
Blocks Do No Place On MC Server

### ISSUE THREAD

**Issue by WCRaptor** [henkelmax/ultimate-car-mod#70]
The issue we are having is being unable to place any block down on the server. It will place then disappear. very frustrating cause it is a cool mod.

We use curse forge as our server and we play on 1.17 with optifine.

**Comment by henkelmax** [comment]
1. Fill out the bug template
2. Make sure the mod is actually installed on the server
3. This mod may have incompatibilities with optifine (We don't officially support it.)
