### ISSUE TITLE
Tanks do not connect vertically.

### ISSUE THREAD

**Issue by SpartanG01** [henkelmax/ultimate-car-mod#72]
**Bug description**
As you can see in the screenshot below vertical tanks do not recognize their connections physically. They connect visually but not systematically. 

**Steps to reproduce the issue**
Connect multiple tanks vertically and attempt to fill them by pipe by only connecting one tank segment via pipe.

**Expected behavior**
On the left is a 3 tank high unit filled with Bio-Diesel and on the right is a 2 tank high unit.  What you would expect to happen is for a liquid pipe between them to create a balance of fluid in the containers resulting in 2 units of 1.5 tanks worth of fluid each. What actually happens is the pipe only fills the portion of the tank it is connected to. 

**Versions**
- Minecraft Version: 1.16.5
- Forge Version: 36.2.0
- Mod Version: 1.0.17

**Other mods**
Modpack: https://www.curseforge.com/minecraft/modpacks/gray-team-modpack

**Screenshots**

![image](https://user-images.githubusercontent.com/39275525/142298202-517155c1-0fd1-49ce-be92-ce0e0d1d111a.png)

**Comment by henkelmax** [comment]
This is completely intended behavior.
The tank you want to insert into is completely full. If you want to fill and empty tank structures you always need to extract at the bottom most tank and insert at the topmost tank.
