### ISSUE TITLE
More transportation options

### ISSUE THREAD

**Issue by Set2Minecraft** [henkelmax/ultimate-car-mod#75]
Some sort of electric engine and a recharging block that can be rotated on any direction. (electric for planes too would be nice)
Also a battery with small, medium, and large sizes that are place able.
I suggest that multiple types of electric energy would be a good idea as using a central generator for large mod packs is very nice

For crafting the engine I suggest 3 types, a powerful one with high energy usage, a jack of all trades, and an efficient engine that has lower performance and therefore has very poor offroad performance. I also suggest that engine specs (hp, energy use, badoffroad(false/true))

Also as a final suggestion, trailers, and that they should be able to carry extra fuel/batteries and/or storage:
for determining what can be put on a trailer (3x2x2 area) i think a grid should pop up with options to take block in inventories and to place it on the trailer (one square block is a 1x1), and that blocks can be placed ontop of each other until it goes over the top (placing a block over the limit triggers this, not the top of a block going over), and rotating blocks also that the trailer should have a 3x2 area and that fuel tanks/batteries should be small(3x1x1),medium(3x1x2), and large (3x2x3) so that the largest battery laying down will fully fill a trailer and go over but still be allowed to transport.

I know that this is a lot and I dont really know what to expect with what too come but please consider them all as separate ideas.

**Comment by henkelmax** [comment]
The mod is feature complete as it is right now. I do not plan to add any features to this mod anymore.
