### ISSUE TITLE
Game Crashes when interacting with almost anything from mod. 

### ISSUE THREAD

**Issue by EonSprite** [henkelmax/ultimate-car-mod#76]
This happens in both Singleplayer and multiplayer for me.

When you click on things like the Gas Station, Split Tank or almost anything with your bare hand the game crashes. 
I found the only way to avoid this is to click on these items with something from the mod like a wrench or whatever. But it is still a really annoying issue as accidently clicking on something crashes your game.

**Comment by henkelmax** [comment]
Please fill out the bug template properly.
