### ISSUE TITLE
Game Crash When interacting with items. 

### ISSUE THREAD

**Issue by EonSprite** [henkelmax/ultimate-car-mod#77]
This happens in both Singleplayer and multiplayer for me.

When you click on things like the Gas Station, Split Tank or almost anything with your bare hand the game crashes.
I found the only way to avoid this is to click on these items with something from the mod like a wrench or whatever. But it is still a really annoying issue as accidently clicking on something crashes your game.

How to reproduce the issue

Get a gas station
Try to open the menu of gas station with bare hand.
See error
Instead of opening the menu it crashes your game

https://gist.github.com/EonSprite/060861a2fefed8992d535bd06774ff20

Versions

Version: 1.17.1
Forge: 37.0.67
Mod Version: 1.17.1-1.0.11.jar
Other mods
Journey Map
Just Enough Items
Guns, Rockets and Atomic Explosions
MinecraftCapes Mod
MrCrayFish's Furniture Mod

**Comment by henkelmax** [comment]
I need the full logs

**Comment by EonSprite** [comment]
> I need the full logs

okay give me a minute

**Comment by henkelmax** [comment]
Please don't paste in the logs. This won't help at all. Please do it like stated in the template: Use github gist and upload the file `.minecraft/logs/latest.log`

**Comment by henkelmax** [comment]
> https://gist.github.com/EonSprite/060861a2fefed8992d535bd06774ff20

As I already said: The **full** logs at this path: `.minecraft/logs/latest.log`

**Comment by henkelmax** [comment]
I can't see any crash in your logs. make sure the game actually crashed the last time you ran it.

**Comment by EonSprite** [comment]
That is what happened the game crashed, i did not open the game since so I actually do not know

**Comment by henkelmax** [comment]
Please try running the game again with the latest forge version and no other mods. If the game still crashes, send me the logs of that.

**Comment by EonSprite** [comment]
> Please try running the game again with the latest forge version and no other mods. If the game still crashes, send me the logs of 

I was able to open it with no issues, so it must be the version or mods that im running it with.

**Comment by henkelmax** [comment]
If you find out in combination with which mod it happens I might be able to help you.

**Comment by EonSprite** [comment]
> If you find out in combination with which mod it happens I might be able to help you.
While only running the latest version of the mod for 1.17.1 it still crashed so it may be with that version.

**Comment by henkelmax** [comment]
> While only running the latest version of the mod for 1.17.1 it still crashed so it may be with that version.

What do you mean with that? I thought it wasn't crashing with only the car mod.

**Comment by EonSprite** [comment]
> 

When you said to try to run it with only the car mod and newest forge I ran it with the 1.18 newest version and newest forge. 

But now I'm saying that the newest 1.17.1 version is the version with the issue.

**Comment by henkelmax** [comment]
> But now I'm saying that the newest 1.17.1 version is the version with the issue.

Then please send me the log of that crash.

**Comment by EonSprite** [comment]
> 

https://gist.github.com/EonSprite/6cacedfb02e291380bb92d23b012352e

**Comment by henkelmax** [comment]
> https://gist.github.com/EonSprite/6cacedfb02e291380bb92d23b012352e

Again. I see no crash.

**Comment by EonSprite** [comment]
> > https://gist.github.com/EonSprite/6cacedfb02e291380bb92d23b012352e
> 
> Again. I see no crash.

Well idk because this was the log of the game crash. 
And I'm pretty sure these are the client logs as these are the logs from the client.

**Comment by henkelmax** [comment]
That's weird. But as said. I can't see any crash, so I won't be able to help you.
