### ISSUE TITLE
server crashing upon starting up

### ISSUE THREAD

**Issue by Nik0dem0-py** [henkelmax/ultimate-car-mod#78]
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**

**Bug description**

~~**Steps to reproduce the issue**~~
~~1. Go to '...'~~
~~2. Click on '...'~~
~~3. Scroll down to '...'~~
~~4. See error~~

**Expected behavior**
When starting up server, the logs go crazy and cause a stackoverflow error.

**Log files**
https://gist.github.com/Nik0dem0-py/253b032c57a17bb1d8fa5b6cf5e7eb43

**Versions**
- Minecraft version - 1.16.5
- Forge version - 36.2.22
- Mod version - latest relase on curseforge 

**Other mods**
Simple Planes (Forge) (by przemykomo)
Bookshelf (by DarkhaxDev)
Just Enough Items (JEI) (by mezz)
Gauges and Switches (by wilechaote)
ConnectedTexturesMod (by tterrag1098)
RandomPatches (Forge) (by TheRandomLabs)
MrCrayfish's Furniture Mod (by MrCrayfish)
Connected Glass (by SuperMartijn642)
AppleSkin (by squeek502)
Entity Culling Fabric/Forge (by tr9zw)
Ranged Wireless Redstone (by Danny_and_Son)
Magnesium (by someoneelsewastaken)
GraveStone Mod (by henkelmax)
Waystones (by BlayTheNinth)
AI Improvements (by QueenOfMissiles)
FastSuite (by Shadows_of_Fire)
Simply Light (by Flanks255)
Waila Harvestability (by squeek502)
Wawla - What Are We Looking At (by DarkhaxDev)
KleeSlabs (by BlayTheNinth)
Chisels & Bits - For Forge (by AlgorithmX2)
Architect's Palette (by Jsburg)
Just Enough Vehicles (by Ozelot5836)
SwingThroughGrass (by exidex)
GeckoLib (by ThanosGecko)
FastFurnace (by Shadows_of_Fire)
Chisel (by tterrag1098)
Macaw's Trapdoors (by sketch_macaw)
Crafting Tweaks (by BlayTheNinth)
Uppers (by vadis365)
WorldEdit (by sk89q)
JourneyMap (by techbrew)
Macaw's Windows (by sketch_macaw)
Smooth Boot (Forge) (by UltimateBoomer)
Neat (by Vazkii)
Ultimate Car Mod (by henkelmax)
FerriteCore (Forge) (by malte0811)
Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)
CaveBiomeAPI [Forge] (by blackgear27)
Client Tweaks (by BlayTheNinth)
NetherPortalFix (by BlayTheNinth)
Macaw's Lights and Lamps (by sketch_macaw)
AttributeFix (by DarkhaxDev)
Traverse Reforged (by Noobanidus)
CoFH Core (by TeamCoFH)
Lighting Wand 🌟 (Forge) (by Snownee_)
Obfuscate (by MrCrayfish)
Inventory Sorter (by cpw)
Macaw's Fences and Walls (by sketch_macaw)
CreativeCore (by CreativeMD)
Moving Elevators (by SuperMartijn642)
Ultimate Plane Mod (by henkelmax)
Macaw's Bridges (by sketch_macaw)
Ore Excavation (by Funwayguy)
Clumps (by Jaredlll08)
Security Craft (by Geforce132)
Dynamic View[Forge/Fabric] (by someaddon)
Comforts (Forge) (by TheIllusiveC4)
Iron Chests (by ProgWML6)
Out Of Sight (by Corosus)
Cyclic (by Lothrazar)
MrCrayfish's More Furniture Mod (by MrCrayfish)
Starlight (w/ Create Compatability) (by SirOMGitsYOU)
MrCrayfish's Vehicle Mod (by MrCrayfish)
Macaw's Roofs (by sketch_macaw)
FastWorkbench (by Shadows_of_Fire)
Mouse Tweaks (by YaLTeR)
Not Enough Crashes (Forge) (by NatanFudge)
Macaw's Doors (by sketch_macaw)
Controlling (by Jaredlll08)
Caves & Cliffs Backport (by blackgear27)
Hwyla (by TehNut)
Macaw's Furniture (by sketch_macaw)
Placebo (by Shadows_of_Fire)
AmbientSounds 5 (by CreativeMD)

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Can you please show me the setup that caused the crash, so that I can reproduce it?

**Comment by henkelmax** [comment]
Closed due to inactivity.
