### ISSUE TITLE
Game/server crashes when you drive into any mob with a car

### ISSUE THREAD

**Issue by Mertini7** [henkelmax/ultimate-car-mod#79]
**Bug description**
Forgeserver crashes when driving into any mob with a car.

**Steps to reproduce the issue**
1. Drive any car
2. Drive into any mob (killing it)
3. Server Crash

**Expected behavior**
Expected mob to be killed and take vehicle damage.

**Log files**

**Versions**
- 1.18.1
- Forge 1.18.1-39.0.10
- [1.18.1] Ultimate Car Mod 1.18.1-1.0.0

**Other mods**
-alexmobs-1.15.1.jar
-Ambientsounds_v5.0.0_mc1.18.1.jar
-Aquaculture-1.18.1-2.3.2.jar
-BiomesOPlenty-1.18.1-15.0.0.66
-camera-1.18.1-1.0.0.jar
-corpse-1.18.1-1.0.0.jar
-Sereneseasons-1.18.1-6.0.0.8.jar
##Unlikely that these mods caused the issue as driving into any mob triggers the crash

**Comment by henkelmax** [comment]
Please fill out the bug template.

**Comment by Mertini7** [comment]
Never used github before, where can i leave the crash log files?

**Comment by henkelmax** [comment]
Upload them on github gist (https://gist.github.com/) and send the link here

**Comment by Mertini7** [comment]
[]((https://gist.github.com/Mertini7/aa89dcfd3e0b9eb723926f26636dc266))

Here you go

**Comment by Mertini7** [comment]
https://gist.github.com/Mertini7/aa89dcfd3e0b9eb723926f26636dc266

**Comment by henkelmax** [comment]
Thanks!

**Comment by Mertini7** [comment]
No problem, thanks for the quick response!

**Comment by Mertini7** [comment]
Edit: Hitting the mob and thus killing it while driving a car crashes the server.

**Comment by henkelmax** [comment]
Alright, will test that, thanks!

**Comment by Mertini7** [comment]
A friend of mine mentioned hitting an Enderman will crash the server regardless

**Comment by henkelmax** [comment]
Alright this should be fixed in the next version.

**Comment by Mertini7** [comment]
Thank you!
