### ISSUE TITLE
can't use car workshop

### ISSUE THREAD

**Issue by jell1y** [henkelmax/ultimate-car-mod#81]
when ever i go onto the car workshop it wont let me use it! i press the button id use for crafting tables or any other useable table but the craft option doesnt even come up! i checked my controls to see if i was using the right one but it still didnt work. pls help

**Comment by henkelmax** [comment]
The workshop is a multiblock structure. Read the wiki for more information.

**Comment by jell1y** [comment]
I tried using it as a big unit and it still didn’t work

**Comment by henkelmax** [comment]
The outter blocks are different blocks than the middle block.
