### ISSUE TITLE
unloading mechanism..

### ISSUE THREAD

**Issue by ORCXodus** [henkelmax/ultimate-car-mod#83]
Ive looked at your wiki and cant seem to find anything relating to it.. but how is liquid / items unloaded from the truck other than by hand? is there a way to connect something to the car to facilitate unloading cargo?  If not it would be a nice addition.. a port on the truck bed that say an importer (Refined Storage) could connect to

**Comment by henkelmax** [comment]
You can only interact with it per hand.
Unfortunately refined storage can't connect to the car, since it is an entity.

**Comment by ORCXodus** [comment]
any way to have the container in the back of the truck act like a chest...it already has the storage properties of a chest... so if the car was an "entity" thats CARRYING a chest... then could not the container be interacted with much like a chest is?

**Comment by henkelmax** [comment]
That's not how it works.
