### ISSUE TITLE
Having trouble getting IE biodiesel to work with UCM

### ISSUE THREAD

**Issue by isaaclepes** [henkelmax/ultimate-car-mod#84]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/car/faq)!**
I saw the previous issues on this topic and believe I followed the advice properly, however I cannot get the vehicles to accept IE's biodiesel.  I can insert it into the gas station, and fill gas cans, but starting the transfer does nothing.  I also cannot use a gas can that contains IE's biofuel.  It says it contains 100mb and will not allow me to use it or place it back into the station.

**I have configured car-server.toml with:**
	[machines.gas_station]
		#Range: 1 ~ 32767
		transfer_rate = 5
		#If it starts with '#' it is a tag
		valid_fuels = ["#car:gas_station", "#forge:biodiesel"]

**and config/car/fuel.toml with:**
["car:bio_diesel"]
	efficiency = 100
["immersiveengineering:biodiesel"]
	efficiency = 100

**I have also tried setting fuel.toml to the forge tag:**
["car:bio_diesel"]
	efficiency = 100
["#forge:biodiesel"]
	efficiency = 100

**Comment by henkelmax** [comment]
You need to make sure you don't have any other fuel in the car.
When you initially spawn a car it has generic fuel. But after you fueled it once with a specific fuel, you need to completely empty the cars fuel tank in order to fuel it with another fuel.
