### ISSUE TITLE
1.18.1 On-Launch Crash

### ISSUE THREAD

**Issue by ShibeTemple** [henkelmax/ultimate-car-mod#85]
**Bug description**
Minecraft fails to launch, crash log pointing to the Cars mod.

**Steps to reproduce the issue**
Open Minecraft with specified mods installed from the CurseForge launcher.

**Expected behavior**
Minecraft successfully launches to the title screen.

**Log files**
https://gist.github.com/ShibeTemple/c356eb71a89dd4441dba80c66f24bc25

**Versions**
- Minecraft version 1.18.1
- Forge version 39.0.79
- Mod version car-1.18.1-1.0.2.jar

**Comment by henkelmax** [comment]
Please properly fill out the template and upload the logs to github gist

**Comment by ShibeTemple** [comment]
Corrected.

**Comment by henkelmax** [comment]
Alright, I tested it with the Forge version you are using and I can't confirm this. Can you please test if this happens for you without any other mods?
If it doesn't please tell me which of your mods causes the issue in combination with the car mod.

**Comment by henkelmax** [comment]
Closed due to inactivity
