### ISSUE TITLE
1.18.2 not supported

### ISSUE THREAD

**Issue by n0uremam** [henkelmax/ultimate-car-mod#86]
**Bug description**
when I load the game it gives me only the mod is not supported 

**Log files**
https://gist.github.com/).](https://gist.github.com/n0uremam/827d1f52fdc5ba60a5bd776162243e80)

**Versions**
- Minecraft version: 1.18.2
- Forge version: 40.0.12
- Mod version: 1.18.1-1.0.2

**Other mods**
1-Minecraft Transit Railway
2-Fabric API
3-Architectury

**Screenshots**
![Screenshot 2022-03-12 164814](https://user-images.githubusercontent.com/84910254/158023041-7d506410-131a-499e-b3fb-2da8dc398c8e.png)

**Comment by henkelmax** [comment]
You are using the 1.18.1 version for 1.18.2

**Comment by n0uremam** [comment]
But I can't find the 1.18.2 car mod version

**Comment by henkelmax** [comment]
Because there isn't a 1.18.2 version
