### ISSUE TITLE
1.18.2-1.0.0 requires Forge 40.0.13

### ISSUE THREAD

**Issue by isaaclepes** [henkelmax/ultimate-car-mod#87]
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**

**Bug description**
![image](https://user-images.githubusercontent.com/54421422/158069416-d4f50a13-a7e1-4463-b3a9-d21c65494723.png)

1.18.2-1.0.0 requires Forge 40.0.13 when forge is  only on 40.0.12

**Comment by henkelmax** [comment]
Update forge

**Comment by isaaclepes** [comment]
My mistake, my web browser was showing me a cached version of the Forge download page.
