### ISSUE TITLE
Road markings aren't selectable

### ISSUE THREAD

**Issue by KongsNutz** [henkelmax/ultimate-car-mod#89]
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**

**Bug description**
Opening the road markings tab with shift+Right click I cannot see any of the road markings

**Steps to reproduce the issue**
1. Go to 'painter tool'
2. Click on 'shift+right click'
3. See no textures of markings'

**Expected behavior**
List of markings should be viewable.

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version 1.18.2
- Forge version 40.0.32
- Mod version 1.18.2

**Other mods**
More minecarts.
Jei.
MrCrayfishes Furniture.
Spark.
Trample Stopper.
Xareos MiniMap.

**Screenshots (Optional)**
![2022-03-29_16 38 22](https://user-images.githubusercontent.com/32734141/160550107-179c8842-99c5-4b93-b7da-777f26cb1f60.png)

**Comment by henkelmax** [comment]
Works perfectly fine for me (car mod + JEI):
![image](https://user-images.githubusercontent.com/13237524/160551109-0efb143a-4a70-48c8-810a-055d5c06a759.png)

Please check if this also happens without any other mods installed. If not, please let me know which mod is causing it.

**Comment by KongsNutz** [comment]
Very strange, I took all other mods away and it's still happening..hm

**Comment by KongsNutz** [comment]
> Works perfectly fine for me (car mod + JEI): ![image](https://user-images.githubusercontent.com/13237524/160551109-0efb143a-4a70-48c8-810a-055d5c06a759.png)
> 
> Please check if this also happens without any other mods installed. If not, please let me know which mod is causing it.

I have tested all and Spark seems to be the culprit.

**Comment by henkelmax** [comment]
Ok, then please also report that issue to spark.

**Comment by henkelmax** [comment]
> Yup have done, thanks

Can you link the issue?

**Comment by henkelmax** [comment]
![image](https://user-images.githubusercontent.com/13237524/160582771-f00364fc-ff53-4c05-bb07-1e742f3e4844.png)

I also can't reproduce it with spark.

**Comment by henkelmax** [comment]
Closed due to inactivity.
