### ISSUE TITLE
Ground Pavement lines doesn't show up on maps.

### ISSUE THREAD

**Issue by ink717** [henkelmax/ultimate-car-mod#9]
Forge 1.16.3

The white/yellow lines on the ground don't show up on  Xaero's Minimap or world map. This might be a texture difference (the way how their map read textures) but wonder whether it can get shown in the future. 

![Screenshot (90)](https://user-images.githubusercontent.com/72815511/95888986-d6aa6200-0d4f-11eb-975a-2ce89efd136b.png)
![Screenshot (89)](https://user-images.githubusercontent.com/72815511/95888989-d6aa6200-0d4f-11eb-8506-9a36be9d7e16.png)

**Comment by henkelmax** [comment]
This is intended behavior.
