### ISSUE TITLE
Server stuck on EntityDataManager WARN

### ISSUE THREAD

**Issue by Gorbiel** [henkelmax/ultimate-car-mod#90]
**Bug description**
Server gets stuck at "Preparing spawn area" and the only message after that is:
"[Server thread/WARN] [minecraft/EntityDataManager]: defineId called for: class de.maxhenkel.car.entity.car.base.EntityCarInventoryBase from class de.maxhenkel.car.entity.car.base.EntityCarLockBase"

**Steps to reproduce the issue**
1. Start the server
2. See the error

**Expected behavior**
Console output doesn't stop and server continues to prepare spawn area and starts up

**Log files**
debug.log https://gist.github.com/Gorbiel/3dc4cb82d8618c8edfccda3770a284f0
latest.log https://gist.github.com/Gorbiel/a162a1b5a2f30ee11301373b03ba5f01
start.bat https://gist.github.com/Gorbiel/fc3e6e3456d37a1de942dfe47ab0d5cc

**Versions**
- Minecraft 1.16.5
- Forge 36.2.31
- Mod 1017

**Other mods**
modlist: https://gist.github.com/Gorbiel/8115667cc0df53e0ba5b7a4bbb8c253e

**Comment by henkelmax** [comment]
This version is not actively supported anymore.
I will only provide support/bug fixes for the last 2 major Minecraft versions (1.17.1 and 1.18.2)
