### ISSUE TITLE
Incompatibility with Cosmos Portals mod

### ISSUE THREAD

**Issue by DankusBaldicusIV** [henkelmax/ultimate-car-mod#92]
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**

**Bug description**
The game crashes if I try to activate a portal from the Cosmos Portal mod while Ultimate Car Mod is installed.

**Steps to reproduce the issue**
1. Install Ultimate Car Mod, Cosmos Portals, and Cosmos Library.
2. Go into a world and use a Unlinked Dimension Container to get a Linked Dimension Container
3. Use the Linked Dimension Container on a Portal Dock with a fully built Portal Frame to activate a portal
4. Game crashes and will keep crashing if you try to reenter the world

**Expected behavior**
Portal activates as normal without crashing

**Log files**

https://gist.github.com/DankusBaldicusIV/138d296c25ef03d5ee6d67b991d9cba6

**Versions**
- Minecraft 1.18.1
- Forge 39.1.2
- Ultimate Car Mod 1.18.1-1.0.2

**Other mods**
Cosmos Portals (cosmosportals-1.18.1-3.1.5.80-universal.jar)
Cosmos Library (cosmoslibrary-1.18.1-5.1.8.10-universal.jar)

**Comment by henkelmax** [comment]
I'll fix this crash, but you should report that issue to Cosmos Portals as it seems to originate from their mod.

**Comment by DankusBaldicusIV** [comment]
Thanks for the quick response! I'll go report the issue to them too then.
