### ISSUE TITLE
I'm not sure...

### ISSUE THREAD

**Issue by DariusVerse** [henkelmax/ultimate-car-mod#99]
Is this how it's supposed to look like?
![Screenshot (38)](https://user-images.githubusercontent.com/108270709/176056050-1e96fae4-b48f-4f96-8db7-1fefecea40cc.png)

**Comment by henkelmax** [comment]
Please read the wiki for instructions

**Comment by DariusVerse** [comment]
I read the wiki but I'm not sure if I did it right...
